### ISSUE TITLE
Parametrize the contract you can use `AccountClient.create_account`

### ISSUE THREAD

**Issue by unparalleled-js** [software-mansion/starknet.py#100]
**Is your feature request related to a problem? Please describe.**
It is not a problem, but I like the transaction management and private key establishment that happens in this method however it is limited to the OZ contract. It would be nice to be able to allow the user to specify any contract to use here (and have it default to the OZ one).

**Describe the solution you'd like**
Allow the user to specify a separate contract to use in `AccountClient.create_account()`

**Describe alternatives you've considered**
Implement outside of lib.

**Additional context**

**Comment by Solpatium** [comment]
I like this idea 👍

**Comment by cptartur** [comment]
Do you have any example account contract to provide instead of OpenZeppelin one? 
We're debating on how to implement different account contracts as it turns out to be more complicated than just modifying  `AccountClient.create_account()` and any example account contracts would be useful.

**Comment by unparalleled-js** [comment]
I was peaking at this one: https://github.com/sambarnes/cairo-multisig

But really, it can be anything so long that it abides by this interface: https://github.com/OpenZeppelin/cairo-contracts/blob/8739a1c2c28b1fe0b6ed7a10a66aa7171da41326/contracts/IAccount.cairo

**Comment by cptartur** [comment]
Thank you! We'll look into it

**Comment by Solpatium** [comment]
@cptartur we should handle this after the RPC work is done.

**Comment by war-in** [comment]
Currently, we are waiting for SW response on this topic. There will be changes in Account deployment, so we have to have more information about it.

**Comment by cptartur** [comment]
`AccoutClient.create_account` has been deprecated and will be removed in next version.
