### ISSUE TITLE
support cairo 1.0 abi.

### ISSUE THREAD

**Issue by wulasite** [software-mansion/starknet.py#1054]
### Feature Request

I have found a contract writtern by cairo 1.0, its abi is diffrent from cairo 0. 
abi type like `
core::felt252
core::integer::u8
core::starknet::contract_address::ContractAddress
`
can not parse by starknet python , or json .
when I use 
`contract = Contract(address=contract_address, abi=abi, provider=account)`
it will raise
**"{'outputs': {0: {'name': ['Missing data for required field.']}}}"** 
error.

**Comment by tomek0123456789** [comment]
Hi, it's an issue we're working on (#825). However, you can interact with Cairo1 contracts by creating calls and sending them, more info [here](https://starknetpy.readthedocs.io/en/latest/guide/account_and_client.html#executing-transactions) and [here](https://starknetpy.readthedocs.io/en/latest/guide/using_existing_contracts.html#raw-contract-calls).
