### ISSUE TITLE
[BUG] `Contract.from` on contract (AbiParsingError)

### ISSUE THREAD

**Issue by ozanbayram** [software-mansion/starknet.py#1081]
### What happened

I can't call 0x01e1f972637ad02e0eed03b69304344c4253804e528e1a5dd5c26bb2f23a8139 contract. I have to use `Contract.from_address` . I can't give ABI manually

### Stack trace

`starknet_py.abi.parser.AbiParsingError: Name 'URI' was used more than once in defined events.`

### Steps to reproduce

```
ADDRESS = 0x1e1f972637ad02e0eed03b69304344c4253804e528e1a5dd5c26bb2f23a8139
node_url = "https://starknet-mainnet.g.alchemy.com/v2/U_b8ufSWw8Q1l4gnTaMGlq7wl4PdW14_"
full_node_client = FullNodeClient(node_url=node_url)
provider = Account(
        address=0x123,
        key_pair=KeyPair.from_private_key(0x123),
        client=full_node_client,
        chain=StarknetChainId.MAINNET,
    )
contract = Contract.from_address_sync(address=ADDRESS, provider=provider, proxy_config=True)
```

### SDK Version

Version: 0.16.1

### Python version

3.8.10

### What operating system are you using?

Linux

### Is there an existing issue for this?

- [X] I have searched the existing issues and verified no issue exits for this problem.

**Comment by drknzz** [comment]
Hey, any specific reason why you can't pass abi manually when creating `Contract`?

It seems that [the event `URI` is defined twice in the ABI](https://starkscan.co/class/0x0003e9099061c29f1bb8252dba98d24d09b9d03cd04cc3c4ef1c0d8d8a3d93c0#code), which is not quite right.

Copying ABI and removing the duplicated event should work.

**Comment by ozanbayram** [comment]
> Hey, any specific reason why you can't pass abi manually when creating `Contract`?
> 
> It seems that [the event `URI` is defined twice in the ABI](https://starkscan.co/class/0x0003e9099061c29f1bb8252dba98d24d09b9d03cd04cc3c4ef1c0d8d8a3d93c0#code), which is not quite right.
> 
> Copying ABI and removing the duplicated event should work.

Because I have many contract in db. 

But I found solution https://starknetpy.readthedocs.io/en/latest/guide/using_existing_contracts.html#raw-contract-calls
```
ADDRESS = 0x1e1f972637ad02e0eed03b69304344c4253804e528e1a5dd5c26bb2f23a8139
call = Call(
    to_addr=ADDRESS,
    selector=get_selector_from_name("isApprovedForAll"),
    calldata=[owner,spender])
# Pass the created call to Client.call_contract
approval = account.client.call_contract_sync(call)
print(approval)
```
Thanks.
