### ISSUE TITLE
[BUG] Wrong type hint for get_state_update return value / BlockStateUpdate annotations.

### ISSUE THREAD

**Issue by TzahiTaub** [software-mansion/starknet.py#1118]
### What happened

The `get_state_update` function under `net.gateway_client` returns `BlockStateUpdate` that is supposed to have a `StateDiff` object in it, however it returns a `BlockStateUpdate` with a `GatewayStateDiff` object. `StateDiff` and `GatewayStateDiff` have no common base type and their fields are different.

### Stack trace

Don't think this helps, but trying to access `state_diff.deprecated_declared_classes` in an object returned from `get_state_update(block_number=block_number)` gives:

```
AttributeError: 'GatewayStateDiff' object has no attribute 'deprecated_declared_classes'
```

### Steps to reproduce

```
import asyncio
from starknet_py.net.gateway_client import GatewayClient

client = GatewayClient(net="testnet")
asyncio.run(client.get_state_update(block_number="latest")).state_diff.deprecated_declared_classes
```

### SDK Version

0.16.1 (though this seems persistent with the main branch)

### Python version

3.9

### What operating system are you using?

Linux

### Is there an existing issue for this?

- [X] I have searched the existing issues and verified no issue exits for this problem.

**Comment by drknzz** [comment]
Hey, thanks for the open issue!

It seems that the `deprecated_declared_classes` is an RPC exclusive field and it's not being provided by gateway.
