### ISSUE TITLE
Show rejection reason in exception

### ISSUE THREAD

**Issue by unparalleled-js** [software-mansion/starknet.py#113]
**Is your feature request related to a problem? Please describe.**

I am unable to make useful assertions on rejection reasons because the exception that gets raised in a generic exception that does not reveal any of the information.

**Describe the solution you'd like**

In `client.wait_for_tx()`, raise a custom error `TransactionRejected(result["message"])` that includes that failure reason from the `result`.

**Describe alternatives you've considered**

Implementing a custom `wait_for_tx()`.

**Additional context**

I was failing to sign a transaction correctly but the error message was not telling me that. I had to set a breakpoint in the lib to find out the details of the failure.

**Comment by unparalleled-js** [comment]
I'm actually seeing some strange properties on the `TransactionInfo` object...

**Comment by cptartur** [comment]
Hey, thanks for the suggestion about custom exceptions.

`TransactionInfo` object are actually created internally in cairo-lang library, they're not part of starknet.py. If you think it's a problem with starknet.py I'd need more details on what's failing.

**Comment by unparalleled-js** [comment]
> `TransactionInfo` object are actually created internally in cairo-lang library, they're not part of starknet.py. If you think it's a problem with starknet.py I'd need more details on what's failing.

Ah, I don't actually think it is a problem with starknet.py but the error is so strange, I would be remiss if I did not at least hint at it.
Basically, I can see some random OS paths in my error message that are definitely not me. I am running `starknet-devnet` as my provider.

**Comment by cptartur** [comment]
Of course. We're actually using `starknet-devnet` for our end-to-end tests and for this limited use it seems to be working most of the time. But I don't dismiss you findings, there may be some hidden problems - I'd recommend investigating more and opening an issue with devnet developers. 

If you manage to find it is actually related to starknet.py, please let us now!

**Comment by unparalleled-js** [comment]
Yay, the PR looks great. I had one comment through (I know it is already merged, but just in case! https://github.com/software-mansion/starknet.py/pull/115/files#r846394692)
