### ISSUE TITLE
Update Starknet Book starknet.py chapter

### ISSUE THREAD

**Issue by drknzz** [software-mansion/starknet.py#1168]
### Feature Request

https://book.starknet.io/ch02-09-starknet-py.html

Some basic info, link to docs, maybe to discord channel

**Comment by ozanbayram** [comment]
I did. https://github.com/starknet-edu/starknetbook/pull/253

**Comment by TobieTom** [comment]
Can I take over this issue? I just recently learned Rust and Cairo so I am taking up a lot of challenges to add to my experience

**Comment by franciszekjob** [comment]
@TobieTom In fact, this issue is not relevant anymore, as starknet book has been integrated into starknet docs, thank you for understanding.
