### ISSUE TITLE
Update Windows installation section in docs

### ISSUE THREAD

**Issue by drknzz** [software-mansion/starknet.py#1173]
### Feature Request

Crypto-cpp-py works on Windows, but some users have problems with LoadLibraryEx errors

edit: edit [docs Windows installation section](https://discord.com/channels/793094838509764618/1138803218571345930/1138804757100777592) with FAQ from [this discord message](https://discord.com/channels/793094838509764618/1138803218571345930/1138804757100777592)

**Comment by 4taras4** [comment]
Have the same issue

`"C:\Users\kiril\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\crypto_cpp_py\cpp_bindings.py", line 58, in load_cpp_lib_windows
    dll_handle = win32api.LoadLibraryEx(dll_name, 0, handle1)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pywintypes.error: (126, 'LoadLibraryEx', 'The specified module could not be found.')`
