### ISSUE TITLE
[BUG] FullNodeClient.get_block_with_tx_hashes wrongly raises

### ISSUE THREAD

**Issue by ClementWalter** [software-mansion/starknet.py#1174]
### What happened

Using

```
[[package]]
name = "starknet-py"
version = "0.17.1"
```

using kakant v0.2.1 RPC

using a `RPC_CLIENT = FullNodeClient(node_url='http://127.0.0.1:5050')`

then

```
await RPC_CLIENT.get_block_with_tx_hashes()
```

raises with 

```
ValidationError: {'block_hash': ['Missing data for required field.'], 'block_number': ['Missing data for required field.'], 'status': ['Missing data for required field.'], 'new_root': ['Missing data for required field.']}
```

while a raw request gives

```
import requests
from pprint import pprint

response = requests.post(
    RPC_CLIENT.url,
    json={
        "jsonrpc": "2.0",
        "method": f"starknet_getBlockWithTxHashes",
        "params": ["latest"],
        "id": 0,
    },
)
pprint(json.loads(response.text))
```

```
{'id': 0,
 'jsonrpc': '2.0',
 'result': {'block_hash': '0x4ef87baa4db112145b96781eeb117e813ef6c3e61f8314fcea995fb5fa3c3fd',
            'block_number': 51,
            'new_root': '0x0',
            'parent_hash': '0x5e83b4ff1002123b1401cdf30d0701aa920d719163f84ec12e2a33873700259',
            'sequencer_address': '0x69420',
            'status': 'ACCEPTED_ON_L2',
            'timestamp': 1693927005,
            'transactions': ['0x6d7d706f5faf04ba8d74646f84009b2b7933fb38eb595fdcb50768e64512ec2']}}
```

### Stack trace

{
	"name": "ValidationError",
	"message": "{'block_hash': ['Missing data for required field.'], 'block_number': ['Missing data for required field.'], 'status': ['Missing data for required field.'], 'new_root': ['Missing data for required field.']}",
	"stack": "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m\n\u001b[0;31mValidationError\u001b[0m                           Traceback (most recent call last)\nCell \u001b[0;32mIn[16], line 1\u001b[0m\n\u001b[0;32m----> 1\u001b[0m \u001b[39mawait\u001b[39;00m RPC_CLIENT\u001b[39m.\u001b[39mget_block_with_tx_hashes()\n\nFile \u001b[0;32m~/.pyenv/versions/3.9.13/envs/kakarot/lib/python3.9/site-packages/starknet_py/net/full_node_client.py:134\u001b[0m, in \u001b[0;36mFullNodeClient.get_block_with_tx_hashes\u001b[0;34m(self, block_hash, block_number)\u001b[0m\n\u001b[1;32m    <a href='file:///Users/clementwalter/.pyenv/versions/3.9.13/envs/kakarot/lib/python3.9/site-packages/starknet_py/net/full_node_client.py?line=123'>124</a>\u001b[0m block_identifier \u001b[39m=\u001b[39m get_block_identifier(\n\u001b[1;32m    <a href='file:///Users/clementwalter/.pyenv/versions/3.9.13/envs/kakarot/lib/python3.9/site-packages/starknet_py/net/full_node_client.py?line=124'>125</a>\u001b[0m     block_hash\u001b[39m=\u001b[39mblock_hash, block_number\u001b[39m=\u001b[39mblock_number\n\u001b[1;32m    <a href='file:///Users/clementwalter/.pyenv/versions/3.9.13/envs/kakarot/lib/python3.9/site-packages/starknet_py/net/full_node_client.py?line=125'>126</a>\u001b[0m )\n\u001b[1;32m    <a href='file:///Users/clementwalter/.pyenv/versions/3.9.13/envs/kakarot/lib/python3.9/site-packages/starknet_py/net/full_node_client.py?line=127'>128</a>\u001b[0m res \u001b[39m=\u001b[39m \u001b[39mawait\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_client\u001b[39m.\u001b[39mcall(\n\u001b[1;32m    <a href='file:///Users/clementwalter/.pyenv/versions/3.9.13/envs/kakarot/lib/python3.9/site-packages/starknet_py/net/full_node_client.py?line=128'>129</a>\u001b[0m     method_name\u001b[39m=\u001b[39m\u001b[39m\"\u001b[39m\u001b[39mgetBlockWithTxHashes\u001b[39m\u001b[39m\"\u001b[39m,\n\u001b[1;32m    <a href='file:///Users/clementwalter/.pyenv/versions/3.9.13/envs/kakarot/lib/python3.9/site-packages/starknet_py/net/full_node_client.py?line=129'>130</a>\u001b[0m     params\u001b[39m=\u001b[39mblock_identifier,\n\u001b[1;32m    <a href='file:///Users/clementwalter/.pyenv/versions/3.9.13/envs/kakarot/lib/python3.9/site-packages/starknet_py/net/full_node_client.py?line=130'>131</a>\u001b[0m )\n\u001b[1;32m    <a href='file:///Users/clementwalter/.pyenv/versions/3.9.13/envs/kakarot/lib/python3.9/site-packages/starknet_py/net/full_node_client.py?line=131'>132</a>\u001b[0m \u001b[39mreturn\u001b[39;00m cast(\n\u001b[1;32m    <a href='file:///Users/clementwalter/.pyenv/versions/3.9.13/envs/kakarot/lib/python3.9/site-packages/starknet_py/net/full_node_client.py?line=132'>133</a>\u001b[0m     StarknetBlockWithTxHashes,\n\u001b[0;32m--> <a href='file:///Users/clementwalter/.pyenv/versions/3.9.13/envs/kakarot/lib/python3.9/site-packages/starknet_py/net/full_node_client.py?line=133'>134</a>\u001b[0m     StarknetBlockWithTxHashesSchema()\u001b[39m.\u001b[39;49mload(res, unknown\u001b[39m=\u001b[39;49mEXCLUDE),\n\u001b[1;32m    <a href='file:///Users/clementwalter/.pyenv/versions/3.9.13/envs/kakarot/lib/python3.9/site-packages/starknet_py/net/full_node_client.py?line=134'>135</a>\u001b[0m )\n\nFile \u001b[0;32m~/.pyenv/versions/3.9.13/envs/kakarot/lib/python3.9/site-packages/marshmallow/schema.py:722\u001b[0m, in \u001b[0;36mSchema.load\u001b[0;34m(self, data, many, partial, unknown)\u001b[0m\n\u001b[1;32m    <a href='file:///Users/clementwalter/.pyenv/versions/3.9.13/envs/kakarot/lib/python3.9/site-packages/marshmallow/schema.py?line=690'>691</a>\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mload\u001b[39m(\n\u001b[1;32m    <a href='file:///Users/clementwalter/.pyenv/versions/3.9.13/envs/kakarot/lib/python3.9/site-packages/marshmallow/schema.py?line=691'>692</a>\u001b[0m     \u001b[39mself\u001b[39m,\n\u001b[1;32m    <a href='file:///Users/clementwalter/.pyenv/versions/3.9.13/envs/kakarot/lib/python3.9/site-packages/marshmallow/schema.py?line=692'>693</a>\u001b[0m     data: (\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    <a href='file:///Users/clementwalter/.pyenv/versions/3.9.13/envs/kakarot/lib/python3.9/site-packages/marshmallow/schema.py?line=699'>700</a>\u001b[0m     unknown: \u001b[39mstr\u001b[39m \u001b[39m|\u001b[39m \u001b[39mNone\u001b[39;00m \u001b[39m=\u001b[39m \u001b[39mNone\u001b[39;00m,\n\u001b[1;32m    <a href='file:///Users/clementwalter/.pyenv/versions/3.9.13/envs/kakarot/lib/python3.9/site-packages/marshmallow/schema.py?line=700'>701</a>\u001b[0m ):\n\u001b[1;32m    <a href='file:///Users/clementwalter/.pyenv/versions/3.9.13/envs/kakarot/lib/python3.9/site-packages/marshmallow/schema.py?line=701'>702</a>\u001b[0m \u001b[39m    \u001b[39m\u001b[39m\"\"\"Deserialize a data structure to an object defined by this Schema's fields.\u001b[39;00m\n\u001b[1;32m    <a href='file:///Users/clementwalter/.pyenv/versions/3.9.13/envs/kakarot/lib/python3.9/site-packages/marshmallow/schema.py?line=702'>703</a>\u001b[0m \n\u001b[1;32m    <a href='file:///Users/clementwalter/.pyenv/versions/3.9.13/envs/kakarot/lib/python3.9/site-packages/marshmallow/schema.py?line=703'>704</a>\u001b[0m \u001b[39m    :param data: The data to deserialize.\u001b[39;00m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    <a href='file:///Users/clementwalter/.pyenv/versions/3.9.13/envs/kakarot/lib/python3.9/site-packages/marshmallow/schema.py?line=719'>720</a>\u001b[0m \u001b[39m        if invalid data are passed.\u001b[39;00m\n\u001b[1;32m    <a href='file:///Users/clementwalter/.pyenv/versions/3.9.13/envs/kakarot/lib/python3.9/site-packages/marshmallow/schema.py?line=720'>721</a>\u001b[0m \u001b[39m    \"\"\"\u001b[39;00m\n\u001b[0;32m--> <a href='file:///Users/clementwalter/.pyenv/versions/3.9.13/envs/kakarot/lib/python3.9/site-packages/marshmallow/schema.py?line=721'>722</a>\u001b[0m     \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_do_load(\n\u001b[1;32m    <a href='file:///Users/clementwalter/.pyenv/versions/3.9.13/envs/kakarot/lib/python3.9/site-packages/marshmallow/schema.py?line=722'>723</a>\u001b[0m         data, many\u001b[39m=\u001b[39;49mmany, partial\u001b[39m=\u001b[39;49mpartial, unknown\u001b[39m=\u001b[39;49munknown, postprocess\u001b[39m=\u001b[39;49m\u001b[39mTrue\u001b[39;49;00m\n\u001b[1;32m    <a href='file:///Users/clementwalter/.pyenv/versions/3.9.13/envs/kakarot/lib/python3.9/site-packages/marshmallow/schema.py?line=723'>724</a>\u001b[0m     )\n\nFile \u001b[0;32m~/.pyenv/versions/3.9.13/envs/kakarot/lib/python3.9/site-packages/marshmallow/schema.py:909\u001b[0m, in \u001b[0;36mSchema._do_load\u001b[0;34m(self, data, many, partial, unknown, postprocess)\u001b[0m\n\u001b[1;32m    <a href='file:///Users/clementwalter/.pyenv/versions/3.9.13/envs/kakarot/lib/python3.9/site-packages/marshmallow/schema.py?line=906'>907</a>\u001b[0m     exc \u001b[39m=\u001b[39m ValidationError(errors, data\u001b[39m=\u001b[39mdata, valid_data\u001b[39m=\u001b[39mresult)\n\u001b[1;32m    <a href='file:///Users/clementwalter/.pyenv/versions/3.9.13/envs/kakarot/lib/python3.9/site-packages/marshmallow/schema.py?line=907'>908</a>\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mhandle_error(exc, data, many\u001b[39m=\u001b[39mmany, partial\u001b[39m=\u001b[39mpartial)\n\u001b[0;32m--> <a href='file:///Users/clementwalter/.pyenv/versions/3.9.13/envs/kakarot/lib/python3.9/site-packages/marshmallow/schema.py?line=908'>909</a>\u001b[0m     \u001b[39mraise\u001b[39;00m exc\n\u001b[1;32m    <a href='file:///Users/clementwalter/.pyenv/versions/3.9.13/envs/kakarot/lib/python3.9/site-packages/marshmallow/schema.py?line=910'>911</a>\u001b[0m \u001b[39mreturn\u001b[39;00m result\n\n\u001b[0;31mValidationError\u001b[0m: {'block_hash': ['Missing data for required field.'], 'block_number': ['Missing data for required field.'], 'status': ['Missing data for required field.'], 'new_root': ['Missing data for required field.']}"
}

### Steps to reproduce

1.  see above

### SDK Version

0.17.1

### Python version

3.9.13

### What operating system are you using?

Mac

### Is there an existing issue for this?

- [X] I have searched the existing issues and verified no issue exits for this problem.

**Comment by tomek0123456789** [comment]
Hi, the problem was fixed in newer versions of starknet.py, because there was no schema for pending blocks. When you use any method that accepts arguments `block_hash` and `block_number` and you don't pass anything to them, the block searched for defaults to `pending`. Those have fewer fields than the "normal" blocks, hence the error in deserialization.

Your manual request, however, has `"latest"` passed to the request and the returned JSON has those "missing" fields.
