### ISSUE TITLE
Add default node providers for `FullNodeClient` constructor

### ISSUE THREAD

**Issue by tomek0123456789** [software-mansion/starknet.py#1180]
e.g.:
```
https://starknet-mainnet.public.blastapi.io/
```

edit: not sure about this one - should be discussed

**Comment by Dagdon** [comment]
I will be able to modify the FullNodeClient constructor to support default providers, allow multiple blockchain networks if needed and use environment variables for security.

**Comment by franciszekjob** [comment]
Hi @Dagdon, this task is not for external contributors, please looks for issues with "good first issue" label, thanks.
