### ISSUE TITLE
different length of wallet address

### ISSUE THREAD

**Issue by viponedream** [software-mansion/starknet.py#1192]
### What happened

same private key
generate the wallet is different  with  agentx.

your :      64
argentx:  66

### Stack trace

same private key
generate the wallet is different  with  agentx.

your :      64
argentx:  66

### Steps to reproduce

1. same private key
generate the wallet is different  with  agentx.

your :      64
argentx:  66

### SDK Version

lastest

### Python version

3.10

### What operating system are you using?

Windows

### Is there an existing issue for this?

- [ ] I have searched the existing issues and verified no issue exits for this problem.

**Comment by viponedream** [comment]
same recovery phrase 
different wallet address with agentx

**Comment by tomek0123456789** [comment]
Hi, do the keys differ in the beginning with zeros? By that I mean that your key is `0x00...` and the one calculated by starknet.py is `0x...`

**Comment by viponedream** [comment]
this site use your project,     https://app.testnet.paradex.trade
some address have 64  and some have 65 of length.

**Comment by tomek0123456789** [comment]
Could you pinpoint where exactly does it happen?

**Comment by ShampooWoo** [comment]
salt.classhash.calldata.cairo version you should check these paeans

**Comment by tomek0123456789** [comment]
Address is represented as [`Felt`](https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_api_openrpc.json#L1265)

`Felt` - "A field element. represented by at most 63 hex digits", taken from [here](https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_api_openrpc.json#L1291)

If you have a reproducible code, then please reopen the issue.

**Comment by tomek0123456789** [comment]
Address is represented as [`Felt`](https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_api_openrpc.json#L1265)

`Felt` - "A field element. represented by at most 63 hex digits", taken from [here](https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_api_openrpc.json#L1291)

If you have a reproducible code, then please reopen the issue.
