### ISSUE TITLE
Add poethepoet to the development dependencies

### ISSUE THREAD

**Issue by ninja342** [software-mansion/starknet.py#1227]
### Feature Request

At the development guide: https://starknetpy.readthedocs.io/en/latest/development.html there are poe commands but there is no mention about poethepoet at dependencies.

**Comment by tomek0123456789** [comment]
Hi, there is a mention of `poethepoet` in `pyproject.toml`, but in the [`dev` section](https://github.com/software-mansion/starknet.py/blob/development/pyproject.toml#L38). The commands should work after invoking `poetry install`.

**Comment by ninja342** [comment]
I am not sure what was the issue but `poetry install` didn't install poe for me. After manually installing poe I am able to use poe commands.

**Comment by tomek0123456789** [comment]
What is your computer and operating system (and is it by any chance MacBook with M1/2 processor)?

**Comment by ninja342** [comment]
It was debian 11 droplet from digital ocean.
