### ISSUE TITLE
Split deprecated schemas to their respective classes based on versions

### ISSUE THREAD

**Issue by ddoktorski** [software-mansion/starknet.py#1249]
Discussed [here](https://github.com/software-mansion/starknet.py/pull/1243#discussion_r1442840446)

**Comment by Jonatan-Chaverri** [comment]
So, whats need to be done is just something like this?
<img width="353" alt="Screenshot 2024-01-23 at 20 19 22" src="https://github.com/software-mansion/starknet.py/assets/25421284/f8320e77-a626-4129-97e3-0d6312386d66">

All the schemas should contains the same code that is currently under `DeprecatedDeclareTransactionSchema` ?

**Comment by Jonatan-Chaverri** [comment]
@ddoktorski please review my PR with the changes I mentioned before. If I'm not correct, I would appreciate if you can please provide more details of the requested changes. Thanks.
