### ISSUE TITLE
Fix dependabot dependencies bump

### ISSUE THREAD

**Issue by ddoktorski** [software-mansion/starknet.py#1254]
Example fails:
production-dependencies: https://github.com/software-mansion/starknet.py/pull/1252
dev-dependencies: https://github.com/software-mansion/starknet.py/pull/1251

Pylint fix requires changes in the `pylint_todo_checker.py`:
https://github.com/software-mansion/starknet.py/pull/1214/files#diff-a7b08b223eea5419fff3fd76ca2986673fdfcbf9c0171abb3b5846e97bd0b8b4

**Comment by Jonatan-Chaverri** [comment]
Is this issue available to pick?

**Comment by ddoktorski** [comment]
Hi @Jonatan-Chaverri Thanks a lot for your interest in contributing to the project. This particular issue is currently being handled by a member of our team. 

Perhaps you'd be interested in taking on #1218? Also, we invite you to browse the entire list of issues. Feel free to ask if you have any questions or need further clarification on any of the tasks :)
