### ISSUE TITLE
Rename contract names from fee to l2

### ISSUE THREAD

**Issue by ddoktorski** [software-mansion/starknet.py#1266]
Investigate how to verify that there is enough STRK tokens on an account to be deployed using `DeployAccountV3`.

Discussed [here](https://github.com/software-mansion/starknet.py/pull/1265/files#r1466818618)

**Comment by ddoktorski** [comment]
Both `L1_GAS` and `L2_GAS` in the `resource_bounds` are specified in FRI, hence we can simply call STRK contract to check a balance. We need to decide whether we should perform this check on the starknet.py side at all, since RPC will throw an error if balance is not sufficient anyway. The current error doesn't include token name, it only provides the information `Account balance is smaller than the transaction's max_fee.`.

**Comment by tkumor3** [comment]
Current RPC response in the case of having insufficient balance is:

```
Client failed with code 55. Message: Account validation failed. Data: perform_validations call failed; failure reason: TransactionFailureReason(code='native_blockifier.PyTransactionExecutionError', error_message='TransactionPreValidationError(TransactionFeeError(L1GasBoundsExceedBalance { max_amount: 1109, max_price: 48000000000000, balance_low: StarkFelt("0x0000000000000000000000000000000000000000000000000000000001ad7180"), balance_high: StarkFelt("0x0000000000000000000000000000000000000000000000000000000000000000") }))').
```

**Comment by Gerson2102** [comment]
Hey I'm Gerson. Member of Dojo Coding. Can I work on this issue? Check my OnlyDust profile, I've contributed to many projects: https://app.onlydust.com/u/Gerson2102

**Comment by franciszekjob** [comment]
Hey @Gerson2102, I've assigned you 👍 . Let me know if you need more information to provide a PR for this issue :).

**Comment by Gerson2102** [comment]
Reading all the comments inside the issue is not clear for me what I have to do. The name of the issue says one thing and the description says completely other thing, as well as the comments inside of it. Do I have to just rename contract names or see how to verify that there is enough STRK tokens on an account to be deployed? If the second one is the case, where should I put that logic? Is there some resoruces that you guys could share with me or not?

**Comment by franciszekjob** [comment]
@Gerson2102 yup, will clarify it and let you know.

**Comment by franciszekjob** [comment]
@Gerson2102 this issue https://github.com/software-mansion/starknet.py/issues/1358 is free and currently it's better to take. Do you want to handle it?

**Comment by Gerson2102** [comment]
@franciszekjob yes man, please.

**Comment by DavidOredu** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknetpy).

### My background and how it can be leveraged
C# programmer here. Interested in taking on your work to rename contract names.

**Comment by Shaarps** [comment]
Mind if I try this one?
