### ISSUE TITLE
[BUG] Error message has a serialized class and is difficult to parse programmatically

### ISSUE THREAD

**Issue by unparalleled-js** [software-mansion/starknet.py#129]
When an error occurs on a contract, the error message includes the class name and is difficult to parse as a string.

## Python version

Python 3.7.9

## Expected Behavior

The error message only contains str or JSON like dict instead of class

## Current Behavior

The error message has a stringified class

## Possible Solution

Convert class to JSON dict first? (fast solution)
Or grab the important fields from the class and compose a nicer error message (ideal solutioin)

## Steps to Reproduce

Create a contract that you know will error (I am using starknet-devnet)
Call method that causes error
See error message.

It looks something like this:
```python
Transaction was rejected with following starknet error: TransactionFailureReason(code='TRANSACTION_FAILED', error_message='Error message: Already initialized\nError at pc=0:118:\nAn ASSERT_EQ instruction failed: 1 != 0.\nCairo traceback (most recent call last):\nUnknown location (pc=0:132)').
```

Notice the part that says `TransactionFailureReason`, that is like a class.. I really just want the code and the `error_message` from it but I have to parse the whole thing as a string.

## Context (Environment)

Makes parsing and forming custom errors challenging.

## Detailed Description

Use more primitive data types.

**Comment by cptartur** [comment]
Good idea, we've should have used code and message from `TransactionFailureReason` instead of the whole class in the first place. 

Fortunately this seems easy to fix.
