### ISSUE TITLE
[refactor] Rename all classes *StarknetBlock* to *BlockWithTxs*

### ISSUE THREAD

**Issue by tkumor3** [software-mansion/starknet.py#1294]
our classes names should be consistent with the names from starknet-spec

**Comment by RuneRogue** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknetpy).

### My background and how it can be leveraged
I am a blockchain and DeFi developer . I am having experience of 8 months . I am currently working as a Blockchain Researcher and Developer. My Experience in programming language like Go , Rust , Java will help me to solve this issue.

**Comment by franciszekjob** [comment]
Included in https://github.com/software-mansion/starknet.py/issues/1358
