### ISSUE TITLE
[BUG] <starknet_py.abi.v2.parser.AbiParsingError>

### ISSUE THREAD

**Issue by ManutdGTA** [software-mansion/starknet.py#1296]
### What happened

starknet_py.abi.v2.parser.AbiParsingError: L1 handler in ABI must be defined '
 'at most once

### Stack trace

address = '0x06b4a7b1a9e8addfbf3b36ffe95033187a0116fc7c7b52adfd5590b26359ec3b'
contract = await Contract.from_address(address=address, provider=account)
this went wrong

address = '0x02e0af29598b407c8716b17f6d2795eca1b471413fa03fb145a5e33722184067'
contract = await Contract.from_address(address=address, provider=account)
this is okay

### Steps to reproduce

1. Mainnet

### SDK Version

0.19.0

### Python version

3.10.13

### What operating system are you using?

Mac

### Is there an existing issue for this?

- [ ] I have searched the existing issues and verified no issue exits for this problem.

**Comment by tkumor3** [comment]
Currently, starknet.py parser doesn't parse correctly if a contract has more than one `l1_handler`
