### ISSUE TITLE
Remove declaration of cairo 0 contracts

### ISSUE THREAD

**Issue by THenry14** [software-mansion/starknet.py#1334]
### Feature Request

Now that it is not possible to declare cairo 0 contracts anymore we should remove a support for it from the sdk altogether

**Comment by enitrat** [comment]
Hi @THenry14  @kkawula,
Starknet-py is not only used for Starknet Mainnet, but also for custom appchains that run Cairo Zero code. As such, we need these features to be back. Could you please revert this commit ?

**Comment by franciszekjob** [comment]
Hey @enitrat, thanks for your report. Will updated you on this once we discuss this idea internally in our team 👍 .
