### ISSUE TITLE
Update `TypedData` in line with `SNIP-12`

### ISSUE THREAD

**Issue by NikitaMishin** [software-mansion/starknet.py#1353]
### Feature Request

Do you guys plan to support snip-12

I see that currently only revision 0 supported https://github.com/starknet-io/SNIPs/blob/main/SNIPS/snip-12.md
https://github.com/software-mansion/starknet.py/blob/345b0ba9a5b717b6635783e9304784d586cd6d0e/starknet_py/net/models/typed_data.py#L17

**Comment by ddoktorski** [comment]
Hi @NikitaMishin
Thank you for opening the issue. Could you please let me know if you need this implementation for a project you're currently working on?

**Comment by NikitaMishin** [comment]
yes but not critical since we can use revision0 but for better user experience eventually good to have support of revision1

> Hi @NikitaMishin Thank you for opening the issue. Could you please let me know if you need this implementation for a project you're currently working on?

**Comment by ddoktorski** [comment]
@NikitaMishin 

I can confirm that we are going to work towards supporting `SNIP-12`. Unfortunately, I am unable to provide a timeline at the moment.
