### ISSUE TITLE
Consider renaming RPC schemes

### ISSUE THREAD

**Issue by franciszekjob** [software-mansion/starknet.py#1358]
### Feature Request

Some RPC models and schemes are named differently than in spec https://github.com/starkware-libs/starknet-specs/tree/master/api.

Examples of potential changes:
- `PendingStarknetBlockWithReceipts` -> `PendingBlockWithReceipts`
- `EstimatedFee` -> `FeeEstimate`
- `FunctionInvocation` -> `FunctionCall`

**Comment by harsha-mangena** [comment]
@franciszekjob, Can I pick this issue?

**Comment by franciszekjob** [comment]
Hi, I think it's going to be better to pick it once #1316 is completed. I'm currently working on it 👍

**Comment by harsha-mangena** [comment]
Sure, Thank You @franciszekjob !

**Comment by Mitish98** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-sdk-for-python).

**Comment by ddoktorski** [comment]
@Mitish98
Currently, we do not sponsor this issue nor any other issues through OnlyDust.

**Comment by franciszekjob** [comment]
Hey @harsha-mangena, #1316 has been closed, so you're welcome to pick this issue 😄

**Comment by harsha-mangena** [comment]
@franciszekjob, Thanks for letting me know!!

**Comment by ScottyDavies** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-sdk-for-python).

### My background and how it can be leveraged
I have experience with RPC APIs and blockchain technology, particularly with StarkNet. My background includes working on integrating and customizing RPC models, making me well-suited to address discrepancies between existing implementations and spec updates

### How I plan on tackling this issue
To approach this problem, you can follow these steps:

Review Spec:
 i will compare the existing RPC models with the StarkNet spec to identify discrepancies.

Update Names: 
Modify the names in the codebase to match the spec (e.g., PendingStarknetBlockWithReceipts to PendingBlockWithReceipts).

Test Changes: 
Ensure that the updated names work correctly by running existing tests and creating new ones if necessary.

Documentation:
 Update any related documentation to reflect the new names and ensure clarity for users.

Deploy:
 Roll out the updated models to the development or staging environment, then to production after verification.

**Comment by franciszekjob** [comment]
Hey @ScottyDavies, I assigned you to this issue 👍

**Comment by ScottyDavies** [comment]
okay, I will start working on it immediately.

**Comment by jcampos2907** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknetpy).

### My background and how it can be leveraged
Im self taught in python, rust, js, sql

**Comment by Ndifreke000** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknetpy).

### My background and how it can be leveraged
I have solid Python skills and a lot of experience in blockchain development. I’ve worked on projects where I built Python tools and decentralized apps, mainly focusing on integrating smart contracts and designing APIs. In one of my recent projects, I created a system that automated revenue sharing through smart contracts, making sure everything worked smoothly and efficiently. These experiences give me the hands-on knowledge needed to tackle challenges like those in StarkNet.

### How I plan on tackling this issue
I would audit the current API structure, using Python to build automated tests to identify inconsistencies in RPC schemes and model names. I’d propose naming conventions aligned with StarkNet and collaborate with the community to implement changes incrementally. To ensure accuracy, I’d create unit tests and documentation for the new API models, establishing a framework for future updates

**Comment by georgegoldman** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknetpy).

### My background and how it can be leveraged
back end developer skilled in Object oriented programming in  python, experience in database models and ORM (SQLAlchemy)

### How I plan on tackling this issue
simply change the name and reflect the change to all related files.

**Comment by Gerson2102** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknetpy).

### My background and how it can be leveraged
I'm Gerson from Dojo Coding community. I have contributed to many projects, you guys can check my OD profile here: https://app.onlydust.com/u/Gerson2102

### How I plan on tackling this issue
I will start by understanding what ia have to do.
Setting up the project.
Doing my own research.
If I'm stuck I will ask for help.
I'll make a PR and wait for your feedback.

**Comment by Gerson2102** [comment]
Hello. In this issue, I already knwo where is the rpc to start changing some of the names of the schemes. They're in `starknet_py/net/schemas/rpc/` right?

One thing that I dont understand, is how to know the new correct names. I checked the resoruces on the issue but still dont get it. I dont know if somebody could help me here with that. I would that's the only thing that is not clear to me. @franciszekjob 

And btw, do you guys have a telegram group or something like that?

**Comment by Gerson2102** [comment]
@ddoktorski

**Comment by franciszekjob** [comment]
@georgegoldman Look up to [Starknet API spec](https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_api_openrpc.json) as reference when changing names.

Yes, here is the link to TG group link https://t.me/starknetpy
