### ISSUE TITLE
Type 'core::integer::i128' is not defined.

### ISSUE THREAD

**Issue by Ophiase** [software-mansion/starknet.py#1366]
### Feature Request

This type is properly defined in Cairo.
I have a contract that use it, but its not recognized by starknet.py.

**Comment by Ophiase** [comment]
I'm going to replace every occurrences of i128 in the ABI with u128 and see what happens.

```python
contract = Contract(address=DEPLOYED_CONTRACT, abi=abi, provider=account)
```

**Comment by Ophiase** [comment]
```python
def replace_i128_with_u128(data):
    if isinstance(data, dict):
        return {key: replace_i128_with_u128(value) for key, value in data.items()}
    elif isinstance(data, list):
        return [replace_i128_with_u128(item) for item in data]
    elif isinstance(data, str):
        return data.replace('i128', 'u128')
    else:
        return data

abi_as_u128 = replace_i128_with_u128(abi)

contract = Contract(address=DEPLOYED_CONTRACT, abi=abi_as_u128, provider=accounts)
```

Result :
``ValueError: Make sure valid ABI is used to create a Contract instance``

**Comment by franciszekjob** [comment]
Hi @Ophiase , support of `i128` is part of [SNIP-12](https://github.com/software-mansion/starknet.py/issues/1353). I'm currently of the process of introducing it to starknet.py, so we can expect it this week or next week at the latest.

**Comment by franciszekjob** [comment]
Closing it, as there wasn't reply for a long time.
