### ISSUE TITLE
[BUG] libcrypto_c_exports.so is missing

### ISSUE THREAD

**Issue by maoryadin** [software-mansion/starknet.py#1396]
### What happened

we have compiled with pyInstaller, run the exe and the error we get is the we are missing libcrypto_c_exports.co

### Stack trace

on mac:
RuntimeError: Couldn't find libcrypto_c_exports

on windows:
Error with LoadLibraryEx is missing.

### Steps to reproduce

1. 

### SDK Version

latest

### Python version

3.10.12

### What operating system are you using?

Windows, Mac

### Is there an existing issue for this?

- [X] I have searched the existing issues and verified no issue exits for this problem.

**Comment by ddoktorski** [comment]
Hi @maoryadin
The issue doesn't seem to be a common one that needs changes in the codebase. Please check the [Windows installation section](https://starknetpy.readthedocs.io/en/latest/installation.html#windows) in our documentation. If you need more help, feel free to ask questions on the dedicated starknet.py [discord support channel](https://discord.com/channels/793094838509764618/928219862327754812).

**Comment by maoryadin** [comment]
> Hi @maoryadin The issue doesn't seem to be a common one that needs changes in the codebase. Please check the [Windows installation section](https://starknetpy.readthedocs.io/en/latest/installation.html#windows) in our documentation. If you need more help, feel free to ask questions on the dedicated starknet.py [discord support channel](https://discord.com/channels/793094838509764618/928219862327754812).

Tried to join the starknet discord server, the invites is paused.

anyway:
`   File "crypto_cpp_py/cpp_bindings.py", line 96, in <module>
  File "crypto_cpp_py/cpp_bindings.py", line 45, in load_cpp_lib
  File "crypto_cpp_py/cpp_bindings.py", line 36, in get_cpp_lib_file
RuntimeError: Couldn't find libcrypto_c_exports
`
it is not a wide or known error?

**Comment by ddoktorski** [comment]
There is a known issue with `libcrypto_c_exports`  during installation on Windows. Have you tried following the steps from the documentation I previously sent?

**Comment by maoryadin** [comment]
> There is a known issue with `libcrypto_c_exports` during installation on Windows. Have you tried following the steps from the documentation I previously sent?

The installation of the mingw-w64 and so is not reallistic if i need this to be compiled and run on a client user.
i will not install and change the client path settings.
There should be another solution for sure
