### ISSUE TITLE
Improve release process

### ISSUE THREAD

**Issue by ddoktorski** [software-mansion/starknet.py#1400]
The current process is a bit manual and requires breaching branch protection.

As a minimal outcome of this issue, the action `Build wheels` should be modified to trigger automatically after creating a new release. Additionally, the [Release checklist](https://starknetpy.readthedocs.io/en/latest/development.html#release-checklist) section in the docs should be updated to include all the relevant information.

**Comment by franciszekjob** [comment]
Closing this as #1440 meets the task's minimum requirement. We can also consider removal of merging dev into master while making a new release.
