### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by ddoktorski** [software-mansion/starknet.py#1410]
Update README to include relevant information for new users or remove its content and leave only a link to the documentation.

**Comment by kkawula** [comment]
I think that one of the most common and quick-to-show usages is calling contract and executing transactions, so I suppose that it will be interesting and helpful if we put such examples in README.
Proposal of README [example usage](https://github.com/software-mansion/starknet.py?tab=readme-ov-file#%EF%B8%8F-example-usage) update.

The new README should contain examples for
- Initialization of Account class
- Calling contract
- Executing a simple transaction
- Sync usage of one method e.g. sth from FullNodeClient

**Comment by franciszekjob** [comment]
Makes sense, all fundamental needs are included there 👍
