### ISSUE TITLE
Add more examples to documentation

### ISSUE THREAD

**Issue by ddoktorski** [software-mansion/starknet.py#1411]
Add more examples to the documentation to also include more advanced use cases.

**Comment by franciszekjob** [comment]
Add examples for https://github.com/software-mansion/starknet.py/pull/1421#discussion_r1701758624

**Comment by martinvibes** [comment]
hello @ddoktorski can I work on this

**Comment by ShantelPeters** [comment]
Hi @ddoktorski please can I be assigned to this issue

**Comment by ScottyDavies** [comment]
Hi @ddoktorski Please can you assign this task to me so I can start working on it immediately

**Comment by GoSTEAN** [comment]
hi

**Comment by franciszekjob** [comment]
Hey, please pick issues with `good first issue` label!
