### ISSUE TITLE
Remove skipping of certain tests

### ISSUE THREAD

**Issue by kkawula** [software-mansion/starknet.py#1419]
Due to an update of devnet [#547](https://github.com/0xSpaceShard/starknet-devnet-rs/pull/547) the bug was removed which now affects our tests. Declaring multiple contracts with the same class hash isn't possible right now.
The short-term solution was to skip these tests.

**Comment by ScottyDavies** [comment]
Hello @kkawula can i work on this?

**Comment by kkawula** [comment]
Hi @ScottyDavies yes sure, but currently we are working on a little test refactor and this issue was intended to start after a few changes, so you can start working from `development` branch in a few days when we merge pr #1448 or you can start now from a branch addressed in the same pr

**Comment by ScottyDavies** [comment]
okay I will get to work

**Comment by kkawula** [comment]
Hi, @ScottyDavies! We've added a lot of `good first issue` labels for newcomers. This is an opportunity to learn the codebase and they are also easier for the beginning. So I would recommend you start with them. This issue requires some context about the project so let's leave it for the future.
