### ISSUE TITLE
[BUG] Error getting tx receipt

### ISSUE THREAD

**Issue by ArielTM** [software-mansion/starknet.py#1423]
### What happened

In certain txs, starknet_py doesn't deserialize Felt well
0x06b7f4ac059de44c9c9d9fc6ddbabe35424e3fe35b97403de41f39a63667ff9b as an example

### Stack trace

```Traceback (most recent call last):
 ...
  File "", line 30, in main
    tx_receipt_test = await node.get_transaction_receipt(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/starknet_py/net/full_node_client.py", line 361, in get_transaction_receipt
    return cast(TransactionReceipt, TransactionReceiptSchema().load(res))
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/marshmallow/schema.py", line 723, in load
    return self._do_load(
           ^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/marshmallow/schema.py", line 910, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'messages_sent': {0: {'to_address': ['Invalid value provided for Felt: 0x023a2aac5d0fa69e3243994672822ba43e34e5c9']}}}
```

### Steps to reproduce

```python
import asyncio
from starknet_py.net.full_node_client import FullNodeClient

node = FullNodeClient("https://starknet-mainnet.public.blastapi.io/rpc/v0_7")

async def main():
    tx_receipt_test = await node.get_transaction_receipt(
        "0x06b7f4ac059de44c9c9d9fc6ddbabe35424e3fe35b97403de41f39a63667ff9b"
    )
    print(tx_receipt_test)


if __name__ == "__main__":
    asyncio.run(main())
```

### SDK Version

v0.7

### Python version

3.11.9

### What operating system are you using?

Mac

### Is there an existing issue for this?

- [x] I have searched the existing issues and verified no issue exits for this problem.

**Comment by ArielTM** [comment]
I don't really get this regex:
https://github.com/software-mansion/starknet.py/blob/5126491b185fc02088b5dda4e6f076f4b30bc72f/starknet_py/net/schemas/common.py#L89

This will match either "0x0" or any hex string with non leading zeros. but hex strings like "0x023a2aac5d0fa69e3243994672822ba43e34e5c9" (which has a leading zero) is a valid Felt afaik.
What is the reason for specifically stating that there are no leading zeros?

**Comment by ArielTM** [comment]
Ok, I now see that it might be a bug in the starknet api spec

https://github.com/starkware-libs/starknet-specs/blob/e5ce8c6f99672d9ddf85a8e1d6ef8e87169d6e8d/api/starknet_api_openrpc.json#L2934

https://github.com/starkware-libs/starknet-specs/blob/e5ce8c6f99672d9ddf85a8e1d6ef8e87169d6e8d/api/starknet_api_openrpc.json#L1303

**Comment by franciszekjob** [comment]
Hey @ArielTM, thanks for the report. Will look into the issue and keep you updated.

**Comment by franciszekjob** [comment]
Hi @ArielTM , FYI: we are fixing the bug in https://github.com/software-mansion/starknet.py/pull/1435
