### ISSUE TITLE
Implement tools that help with reading compiled contracts

### ISSUE THREAD

**Issue by kkawula** [software-mansion/starknet.py#1455]
Add a class/methods that helps with importing [scarb](https://docs.swmansion.com/scarb/docs.html) output. It gives you everything needed to declare the contract.
- reads sierra
- reads casm
- reads abi
- calculates compiled_contract_casm

Additionally, add an example in docs. 

For reference our implementation for test purposes [load_contract](https://github.com/software-mansion/starknet.py/blob/development/starknet_py/tests/e2e/fixtures/misc.py#L72C5-L72C18).

**Comment by ShantelPeters** [comment]
Hi @kkawula can i please be assigned to this issue?

**Comment by kkawula** [comment]
Hi @ShantelPeters yes, you can take it. Can you give pr this week? FYI: we have similar functionality in our test, so that can inspire you. [load_contract](https://github.com/software-mansion/starknet.py/blob/development/starknet_py/tests/e2e/fixtures/misc.py#L72)

**Comment by ShantelPeters** [comment]
Okay sir @kkawula

**Comment by Constantine234** [comment]
I have an Idea on how to do this i dont know if i can contribute to this

**Comment by kkawula** [comment]
Hi @Constantine234! Currently someone is working on this issue, so at this time you can't, but we have a few issues labeled as `good first issue` so feel free to choose something for yourself.

**Comment by kkawula** [comment]
Hi @Constantine234 this issue is free to take, are you still interested in it?

**Comment by Constantine234** [comment]
yes sir I am interested

**Comment by Constantine234** [comment]
@kkawula when will you want this to be ready?

**Comment by kkawula** [comment]
It would be great if manage to open pull request in one week and request me for the first review

**Comment by Constantine234** [comment]
okay so that is to say it should be done before next week right ? @kkawula

**Comment by kkawula** [comment]
yes, something like that

**Comment by Constantine234** [comment]
then trust me on this is done I will start working on it tomorrow to Wednesday @kkawula

**Comment by Constantine234** [comment]
@kkawula Pull request will be done tomorrow thank you

**Comment by Constantine234** [comment]
@kkawula i have done the PR this is the code #1472
you can go check it thank you and if there is any changes let me know

**Comment by ManvithaMolakala** [comment]
Hi @kkawula, i would like to contribute to this issue if noone else is working on it. Also, can we connect on telegram to discuss?

**Comment by KXYWISE** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknetpy).

### My background and how it can be leveraged
Intermediate in Python and Java. 

### How I plan on tackling this issue
Initialization:The class takes in file paths for the Sierra, CASM, and ABI files.Methods:read_sierra(): Loads the Sierra file.read_casm(): Loads the CASM file.read_abi(): Loads the ABI file.calculate_compiled_contract_casm(): Uses the loaded data to compute a unique value for the compiled contract (this is a placeholder and should be replaced with the actual computation).Usage:Create an instance of ScarbOutputImporter, provide the file paths, and call load_all() to load all the data.Then, call calculate_compiled_contract_casm() to compute the result.This structure should give you everything needed to handle importing the Scarb output and computing the required values for declaring the contract. You can extend the placeholder logic in calculate_compiled_contract_casm() based on how the contract declaration process is defined in Starknet.

**Comment by tumutech** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknetpy).

### My background and how it can be leveraged
I have been implemented tools using Python and i can borrow concepts from similar implementations to handle this issue.

### How I plan on tackling this issue
I will use inspiration from the https://github.com/software-mansion/starknet.py/blob/development/starknet_py/tests/e2e/fixtures/misc.py#L72C5-L72C18 , then i will test the implementation solution if it solves the problem i will go ahead and write a documentation on how the tool can be used.

**Comment by ManvithaMolakala** [comment]
Hi @kkawula 

Please confirm the following approach for this issue:
I will add the function load_contract that takes input as contract_name,  package name and outputs casm, sierra in contract_utils.py.

**Comment by kkawula** [comment]
Hi @ManvithaMolakala 
Yes, it sounds good, remember that Scarb generates artifacts file in `target/dev`, where we can find paths to outputs and casm isn't always generated, it must be marked as true in `Scarb.toml` 
```
[[target.starknet-contract]]
casm = true
sierra = true
```
