### ISSUE TITLE
Check contracts formatting

### ISSUE THREAD

**Issue by franciszekjob** [software-mansion/starknet.py#1457]
### Feature Request

Check cairo contracts formatting in workflow by using `scarb fmt --check`.

**Comment by ScottyDavies** [comment]
Hello @franciszekjob can i work on this?

**Comment by ShantelPeters** [comment]
Hi @franciszekjob i will love to work on this issue

**Comment by franciszekjob** [comment]
Hey @ScottyDavies , @ShantelPeters , you're welcome to open a PR for it :).
