### ISSUE TITLE
Revert deprecation of Cairo0 / V1 transactions

### ISSUE THREAD

**Issue by enitrat** [software-mansion/starknet.py#1479]
### Feature Request

v1 transactions were removed in this PR https://github.com/software-mansion/starknet.py/pull/1451/files
As part of this epic: https://github.com/software-mansion/starknet.py/issues/1334

This is problematic for people that are still using CairoZero and V1 transactions, notably for:
- local development (katana, devnet, etc do not have the same restrictions as sn mainnet)
- appchain teams (that run a custom stack and still use CairoZero / v1 tx)

Please revert the commits involved to bring back the feature.

**Comment by franciszekjob** [comment]
Hey @enitrat, thanks for your report. Will update you on this once we discuss the idea internally in our team 👍 .

**Comment by franciszekjob** [comment]
@enitrat fyi: We reverted the changes :).

**Comment by enitrat** [comment]
Thank you!
