### ISSUE TITLE
SNIP-9

### ISSUE THREAD

**Issue by NikitaMishin** [software-mansion/starknet.py#1516]
### Feature Request

Do you guys support 
1) snip-9
2) and  snip-12 revision-1?

**Comment by NikitaMishin** [comment]
any eta on (1)? @franciszekjob 
or any idea how hard to add?

**Comment by franciszekjob** [comment]
I can update you in the next days about the possible timeline 👍

**Comment by NikitaMishin** [comment]
@franciszekjob  looking forward to update

**Comment by franciszekjob** [comment]
@NikitaMishin earliest we could address it, is in about 1.5/2 weeks I believe.
I assume you need it for development in https://github.com/LayerAkira?

**Comment by NikitaMishin** [comment]
@franciszekjob  yep, for now can leverage starknet-js but looking forwards for its implementation on python side as well!

**Comment by franciszekjob** [comment]
Moved to #1517.
