### ISSUE TITLE
Support SNIP-9

### ISSUE THREAD

**Issue by franciszekjob** [software-mansion/starknet.py#1517]
### Feature Request

Add support for [SNIP-9](https://github.com/starknet-io/SNIPs/blob/main/SNIPS/snip-9.md)

Reference PRs in starknet.js:
- https://github.com/starknet-io/starknet.js/pull/1202
- https://github.com/starknet-io/starknet.js/pull/1208

**Comment by baitcode** [comment]
I'd love to contribute. If you don't mind.

**Comment by franciszekjob** [comment]
Hi @baitcode :) sure. Is the description clear to you or you need more context/information from me?

**Comment by franciszekjob** [comment]
@baitcode We don't have deadline for this. Could you assign via onlydust platform please?

**Comment by franciszekjob** [comment]
@baitcode assigned you to it, good luck 😄

**Comment by franciszekjob** [comment]
Hi @baitcode, how's the progress 😄 ?

**Comment by baitcode** [comment]
Only starting. Will create branch soon.

**Comment by baitcode** [comment]
You can check progress on that raft PR. The implementation is mostly done. Tests and documentation are missing. This will take me some time to finalise.

**Comment by baitcode** [comment]
@franciszekjob I've made draft PR and got circular dependency error. I might've mistakenly put OutsideTransaction together with other transactions. Could you please take a look and provide me with the advise on how to better organise code?

**Comment by baitcode** [comment]
@franciszekjob I've read couple more times and realised that there are more issues than I though. Broadcast of sucj a transaction is different as well. Will continue with implementation. But would love to hear your though about  structural organisation. I'm not yet good with module responsibilities.

**Comment by baitcode** [comment]
Figured it out. 
I need to first add client models, then marshmellow serialisers for it, then add it to client, then add it to account.

**Comment by baitcode** [comment]
@franciszekjob You can start the review. I'm fighting with linter and documentation atm.
