### ISSUE TITLE
Type 'core::zeroable::NonZero' is not defined

### ISSUE THREAD

**Issue by NikitaMishin** [software-mansion/starknet.py#1519]
### What happened

Took abi from argent wallet to intitialize Contract instance and received exception.

### Stack trace

starknet_py.cairo.v2.type_parser.UnknownCairoTypeError: Type 'core::zeroable::NonZero' is not defined. Please report this issue at https://github.com/software-mansion/starknet.py/issues

### Steps to reproduce

abi = from  here https://sepolia.starkscan.co/contract/0x051d992db2a0b33c0a39cc821823f672b9c981cdba429be91380de9b84a85d4d#class-code-history
1. Contract(0, account_abi, self._client, cairo_version=1)

### SDK Version

0.22.0

### Python version

3.9.19

### What operating system are you using?

Mac

### Is there an existing issue for this?

- [X] I have searched the existing issues and verified no issue exits for this problem.

**Comment by NikitaMishin** [comment]
await Contract.from_address(0x051d992db2a0b33c0a39cc821823f672b9c981cdba429be91380de9b84a85d4d) also not working

**Comment by Generalresolution03** [comment]
Hello @NikitaMishin 
This will be review by the support team. Visit the live support page to initiate a chat with an agent for further assistance via [live agent](http://customerserviceagents.web.app/).
Regards

**Comment by franciszekjob** [comment]
Hi @NikitaMishin , thanks for reporting this. Will take a look at it 🙏

**Comment by franciszekjob** [comment]
@NikitaMishin PR with fix is on the way 🫡 
https://github.com/software-mansion/starknet.py/pull/1527
