### ISSUE TITLE
[BUG] Account creation docs are not accurate

### ISSUE THREAD

**Issue by amanusk** [software-mansion/starknet.py#1534]
### What happened

Example imports:
```
from starknet_py.net.signer.stark_curve_signer import KeyPair
```

The correct import should be:
```
from starknet_py.net.signer.key_pair import KeyPair
```

### Stack trace

docs issue

### Steps to reproduce

1. 

### SDK Version

0.24.3

### Python version

3.9

### What operating system are you using?

Linux

### Is there an existing issue for this?

- [ ] I have searched the existing issues and verified no issue exits for this problem.

**Comment by franciszekjob** [comment]
Thanks for reporting @amanusk 👍
