### ISSUE TITLE
class_hash instead of implementation_address in proxy contracts

### ISSUE THREAD

**Issue by war-in** [software-mansion/starknet.py#161]
The proxy contract will work with a class rather than a contract, that is implementation_address would change to class_hash.

There is an implementation of ArgentProxyCheck and OpenZeppelinProxyCheck in our project, so we should check how they will manage this change.

**Comment by cptartur** [comment]
Partially resolved in #190 

Waiting for OZ, Argent to update their proxies so we can verify
