### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Qupday** [software-mansion/starknet.py#219]
pip install starknet.py Failed!
## Python version

python38
## Current Behavior

install failed
## Steps to Reproduce

1. When I first install starknet.py, catch many errors; any dependence libs is required?
2.
3.
4.

**Comment by cptartur** [comment]
Hey, you didn't really give us much details about your problem, so I cannot help you much. 

Starknet.py requires cairo-lang which itself needs some dependencies outside of pypi to work, [see this guide.](https://www.cairo-lang.org/docs/quickstart.html)
