### ISSUE TITLE
[BUG] The CairoSerializer cannot handle names starting with a underscore

### ISSUE THREAD

**Issue by ca11ab1e** [software-mansion/starknet.py#260]
I've a Cairo contract using names starting with a underscore. And using the `FunctionCallSerializer` for get back data from Cairo to Python (to decode transactions return data) will raise:

```python
ValueError: Field names cannot start with an underscore: '_name`
```

It's a namedtuple limitation, from here:
https://github.com/software-mansion/starknet.py/blob/36acd9f75e189b94a75ac413f99e72984d1e3121/starknet_py/utils/data_transformer/data_transformer.py#L207-L209

## Python version

All.

## Expected Behavior

Names starting with a underscore should not be a problem.

## Current Behavior

```python
ValueError: Field names cannot start with an underscore: '_name`
```

## Possible Solution

1. We could use the `rename` kwargs from the namedtuple, but will would loose the real name then.
2. An idea using dataclasses, but we would then loose the tuple comparison (which is mandatory to keep):
  ```python
   from dataclasses import make_dataclass

   # instead of the namedtuple:
   result = make_dataclass("Result", [(k, v) for k, v in ...], order=True, frozen=True, slots=True)
```
3. :heart_decoration: https://github.com/ksamuel/drecord

## Steps to Reproduce

1. Use a name starting with a underscore, in any Cairo method.
2. Use  `FunctionCallSerializer.to_python()`. 
3. See the exception.

## Context (Environment)

The issue is quite big, because we're using the `FunctionCallSerializer` in the [Ape StarkNet](https://github.com/ApeWorX/ape-starknet) plugin to decode transactions return data. The goal is to leverage all the fantastic work you've already done to decode all kind of data types (like arrays, and custom complex structs).

## Possible Implementation

I like the 3<sup>rd</sup> idea. If you think it's something you would like to implement, I could give a try.

**Comment by Arcticae** [comment]
Drecord doesn't have equality implemented which is quite a complex feature. We have a couple of ideas we want to try - @war-in  will handle this one.

**Comment by Arcticae** [comment]
Or me if he's too busy ;)

**Comment by ca11ab1e** [comment]
I am doing it :)

The problem here, is that such a Cairo function will break the serializer:

```cairo
func foo(_arg : felt):
    return ()
end
```
`_arg` is not allowed in namedtuples.

**Comment by war-in** [comment]
Yeah, I know that my comment doesn't close the issue, but you mentioned FunctionCallSerializer and I thought that you didn't know about CairoSerializer because it is the relatively new one.

**Comment by ca11ab1e** [comment]
Oh OK :)
I know that `FunctionCallSerializer` calls `CairoSerializer` under the wood, and as `FunctionCallSerializer` is the new `DataTransformer` name, I used it. But yes, both have the same issue at the end.
