### ISSUE TITLE
Typo in pyproject.toml

### ISSUE THREAD

**Issue by pedrobeirao** [software-mansion/starknet.py#31]
pyproject.toml in line 25 should be:

test_e2e.shell = "starknet-devnet --host localhost --port 5000 ; DEVNET_PID=$! && sleep 1 && coverage run -m pytest starknet/tests/e2e; kill $DEVNET_PID"

**Comment by pedrobeirao** [comment]
Local web page not created when running poe test. 404 error generated in

http://localhost:5000/

**Comment by Arcticae** [comment]
Hey, this ampersnad sign was intened to be there for this to function properly, the devnet process runs in the background while the tests are run in the foreground. After finishing testing and checking coverage, we kill the process. Let me know if i can help out on this one further.
