### ISSUE TITLE
poe test error

### ISSUE THREAD

**Issue by pedrobeirao** [software-mansion/starknet.py#32]
Local web page not created when running poe test. 404 error generated in

http://localhost:5000/

**Comment by Solpatium** [comment]
Hi! Do you have anything running on 5000 before running tests? If not, can you still replicate the issue on latest master branch?

**Comment by Solpatium** [comment]
Now I think you are trying to get `http://localhost:5000/` while running devnet, it won't work as it doesn't define `/` route.
