### ISSUE TITLE
Wrap all the exceptions raised by StarkNet.py with custom ones.

### ISSUE THREAD

**Issue by Radinyn** [software-mansion/starknet.py#324]
Currently, StarkNet.py uses generic errors throughout the code.

This behaviour is not ideal because:
-  it doesn't allow for catching errors from this package separately,
- it doesn't differentiate between unexpected and expected errors.

The new exceptions could be introduced as a non-breaking change by using inheritance (possibly multiple inheritance).

**Comment by cptartur** [comment]
Can you show examples of some places where this change would be beneficial? I'd rather not create a separate exception structure when python has quite a good collection of built in ones.

**Comment by Radinyn** [comment]
For example in [Protostar](https://github.com/software-mansion/protostar) we need to monitor the places where exceptions are being raised in order to avoid unexpected crashes on non-fatal issues. This would allow other developers to more safely use StarkNet.py in their projects. The second benefit is readability - after seeing an exception you know whether it was expected (custom exception) or unexpected (generic error). Expected errors provide information to the user that they are using the functionality in a wrong way. Unexpected errors allow us to see when the package is not working properly and (could) tell us to later report it as a bug.

**Comment by cptartur** [comment]
While I see your point I think it's not practical to replace exceptions with custom ones and I don't really like the wrapping approach. I think it's fine for a python package to use built in exceptions in 99% cases and custom ones would mostly increase confusion. What we could consider doing is better documenting exceptions that can be thrown from public methods so it's known on your side that the failure was in fact starknet.py exception and not a random runtime failure.
