### ISSUE TITLE
Move contents `client_models` to `net.models`, deprecate `client_models`.

### ISSUE THREAD

**Issue by cptartur** [software-mansion/starknet.py#347]
**Is your feature request related to a problem? Please describe.**

Refactor starknet.py so all our client related models are in `net.models` module.

**Describe the solution you'd like**

Move contents of `client_models.py` to separate files in `net.models` and deprecate it.

**Describe alternatives you've considered**

none

**Additional context**

n/a

**Comment by cptartur** [comment]
Blocked mostly by #376

**Comment by cptartur** [comment]
We should consider defining our own dataclasses for transactions once we move them.

**Comment by tomek0123456789** [comment]
Will be implemented in #1047
