### ISSUE TITLE
Unable to get block [BUG]

### ISSUE THREAD

**Issue by unparalleled-js** [software-mansion/starknet.py#365]
When I try to get the latest block on a fresh state (e.g. just start devnet for first time), I get an integer serialization error.

Here is an example of the failing schema:

```python
{'gas_price': '0x174876e800', 'block_number': 0, 'block_hash': '0x0', 'transaction_receipts': [], 'parent_block_hash': '0x0', 'status': 'ACCEPTED_ON_L2', 'transactions': [], 'starknet_version': '0.10.0', 'sequencer_address': '0x6c4ae5be723ab0402cd675e7f8e1cf5a775e972e6f080ad0b842f40ec202a69', 'state_root': '', 'timestamp': 1662661863}
```

## Python version
3.9

## Expected Behavior

Is able to decode response data

## Current Behavior

```
---> 49         return int(value, 16)
     50 
     51 

ValueError: invalid literal for int() with base 16: ''
```

## Possible Solution

Handle empty state root in block schema

## Steps to Reproduce

1. Start devnet
2. Use gateway client on devnet to try and get latest block
3. Notice error
4.

## Context (Environment)

Working on plugin for Ape framework

## Detailed Description

Handle empty strings - maybe conver them to `0x0` ?

## Possible Implementation

Convert empty string to `"0x0"` or ignore int() call when it is empty string or make it None and optional

**Comment by war-in** [comment]
Hi, thank you for reporting! Although we would like to avoid such errors I don't think it's a problem with starknet.py. Devnet returns `new_root` when fetching through FullNodeClient, but does not return `state_root` (which is equivalent) for GatewayClient. In my opinion, it would be better to create an issue on the devnet repo, because we don't want to add default parameters for the required fields

**Comment by war-in** [comment]
It seems that your issue was fixed in [this devnet PR](https://github.com/Shard-Labs/starknet-devnet/pull/270). I am running devnet from the master branch and everything is working. Tell us if it is working for you too so we could close the issue :)

**Comment by war-in** [comment]
Ok, so I'm closing this issue and fill free to reopen it if there still will be problems :)
