### ISSUE TITLE
Add `Setup` section to documentation

### ISSUE THREAD

**Issue by war-in** [software-mansion/starknet.py#394]
**Is your feature request related to a problem? Please describe.**

Our docs can make users confused about creating an `AccountClient`. In many places we do 

> `account = await AccountClient.create_account(...)`
> ` await account.send_transaction(...)`

without explicitly feeding an account with fee tokens. 
Users don't see that after creating an account they have to send some tokens to its address to be able to make transactions.

**Describe the solution you'd like**

The docs should be updated. I would add a `Setup` section in which we are showing how to create and add tokens to an account. Then in all tests, we shouldn't make any accounts.

**Comment by cptartur** [comment]
Good call: I'd go a step further and remove all usages of `AccountClient.create_account` from the docs (while adding `Setup` section) due to its pending deprecation
