### ISSUE TITLE
[BUG] Compiled Account Contract is missing `__validate__``

### ISSUE THREAD

**Issue by unparalleled-js** [software-mansion/starknet.py#401]
The compiled account contract in `net.account.compiled_account_contract` is outdated and missing `__validate__` and `__validate_delcare__` methods.

## Python version

3.9

## Expected Behavior

The account contracts are up to date with the `Account.cairo` from `OpenZeppelin/cairo-contracts` at least contain `__validate__` and `__validate_declare__` implementations.

## Current Behavior

The compiled contract is missing `__validate__` and `__validate_delcare__` methods.

## Possible Solution

Replace content with re-compiled account from Open Zeppelin 0.4.0b0

## Steps to Reproduce

1.
2.
3.
4.

**Comment by war-in** [comment]
Hi, we are deprecating the `AccountClient.create_account` method, so we haven't updated the `COMPILED_ACCOUNT_CONTRACT`. An Account can be created using the Deploy transaction and we recommend doing it this way.
