### ISSUE TITLE
[BUG] GatewayClient.get_block `block_hash` not supporting `"pending"`, `"latest"` literals in 0.10.1 integration

### ISSUE THREAD

**Issue by cptartur** [software-mansion/starknet.py#423]
This requires some more investigation but it seems like 0.10.1 changed the support for literals for `blockHash`, at least in `get_block` endpoint.

We should investigate if it was supported in previous version (perhaps it's a bug in starknet.py), bug in 0.10.1 integration, or desired changed to starknet.

**Comment by drknzz** [comment]
It seems that it was like this the whole time? At least I don't see where it has been changed.
`GatewayClient.get_block` can take the "latest" / "pending" block tag in both `block_hash` and `block_number` parameters though. Later the id is [changed to](https://github.com/software-mansion/starknet.py/blob/64037f2000cd62faa88f4f7e4a3fdc3f14f34a59/starknet_py/net/gateway_client.py#L387) `{"blockNumber": "latest"}` as it cannot be sent as `blockHash`.
