### ISSUE TITLE
Use `"pending"` block in `AccountClient`.

### ISSUE THREAD

**Issue by cptartur** [software-mansion/starknet.py#429]
We currently use `"latest"` because of lack of support for pending in devnet. This should be changed in `devnet` and updated in our code.

**Comment by Solpatium** [comment]
I think devnet already supports pending block.

**Comment by cptartur** [comment]
https://github.com/Shard-Labs/starknet-devnet/pull/313

**Comment by cptartur** [comment]
PR resolving block should be merged now
