### ISSUE TITLE
Move all test fixtures to separate directories

### ISSUE THREAD

**Issue by cptartur** [software-mansion/starknet.py#441]
**Is your feature request related to a problem? Please describe.**

Currently the `conftest.py` is very cluttered and hard to navigate.

**Describe the solution you'd like**

Fixtures should be in separate files.

It is possible to create directories like `fixtures` with files for specific types of fixtures and then in top-level `conftest.py` "import" them using `pytest_plugins = ["path_to_fixture_directory", ...]`

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by war-in** [comment]
Maybe it is a good opportunity to create the main `conftest.py` file and add there some fixtures needed by unit tests. What do you think?

**Comment by cptartur** [comment]
I think we can do that, do you still want to follow the suggested approach of creating directory for fixtures and importing them as plugins?

**Comment by war-in** [comment]
For sure!
