### ISSUE TITLE
Add testing of l1<>l2 messages for messaging module

### ISSUE THREAD

**Issue by Arcticae** [software-mansion/starknet.py#483]
Supposedly, there is a plugin for devnet which integrates with hardhat. 
It's important, a minimal thing would be to run it on demand, or per-deploy, so we are sure that thing is working. 
I know that YAGNI, but we have the feature, and if it's there - it should be working (or be removed).

**Comment by cptartur** [comment]
Connected with #579

**Comment by war-in** [comment]
We decided to entirely remove this module
