### ISSUE TITLE
Create a solution for code to integrate and typecheck nicely with mypy

### ISSUE THREAD

**Issue by Arcticae** [software-mansion/starknet.py#492]
When using contracts from static ABI, we could generate statically some types and cast contract objects, so that they could typecheck properly.

**Comment by Arcticae** [comment]
bump

**Comment by cptartur** [comment]
Blocked by #547

**Comment by cptartur** [comment]
@Arcticae do we still want to support this feature?

**Comment by Arcticae** [comment]
It's still a good idea IMHO to autogenerate types from ABI

**Comment by tomek0123456789** [comment]
Too much effort for too little outcome
