### ISSUE TITLE
Simplify import paths of important functionalities 

### ISSUE THREAD

**Issue by Solpatium** [software-mansion/starknet.py#503]
**Is your feature request related to a problem? Please describe.**
Currently users can import `Contract` right from `starknet_py.contract`, but to use `AccountClient` they have to use `starknet_py.net.account.account_client`, which is not obvious, especially for newcomers.

**Describe the solution you'd like**
I think exposing nested modules in top-level directory could do the job here. For instance we could add `{account,client,signer}.py` files next to contract.py and just expose imports from nested modules. I am open to other solutions.

**Describe alternatives you've considered**
Moving the whole structure is a bad idea:
- we want to have it organised nicely 
- breaking changes

Using imports in `__init__` files:
- often causes problems with cyclic imports that are difficult to solve

**Comment by cptartur** [comment]
#562
