### ISSUE TITLE
Improve error message for when contract is not found

### ISSUE THREAD

**Issue by unparalleled-js** [software-mansion/starknet.py#505]
**Is your feature request related to a problem? Please describe.**

I am currently facing a problem that results in this error:

```
starknet_py.net.client_errors.ContractNotFoundError: Client failed: No contract found for identifier: pending
```

It would be helpful for me to know something about the contract, like perhaps its class hash? For debugging purposes.
Also the word before "identifier" should maybe say "block" because it sounds like "pending" is referring to a contract identifier but I am pretty sure it is a block, but it might not be obvious enough.

**Describe the solution you'd like**

```
starknet_py.net.client_errors.ContractNotFoundError: Client failed: No contract with hash 1234123125 found for block identifier: pending
```

**Describe alternatives you've considered**

I thought about this for 15 seconds and I am not sure exactly but will keep it in mind, thanks.

**Additional context**

**Comment by cptartur** [comment]
I think it makes sense to add this.
