### ISSUE TITLE
Use typed dicts for Abi

### ISSUE THREAD

**Issue by drknzz** [software-mansion/starknet.py#512]
Originated in #504

## Is your feature request related to a problem? Please describe.

Currently Gateway uses Abi defined vaguely as a list of dicts.

RPC abi is specified in the [specs](https://github.com/starkware-libs/starknet-specs/blob/refs/tags/v0.2.1/api/starknet_api_openrpc.json#L1741).
There is no official specification for gateway abi.
Although when looking into cairo-lang I didn't spot any fields that would be possible other than these already included in the dataclasses.

## Describe the solution you'd like
Find out whether there are any differences between `abi` in RPC and Gateway.
Use Abi dataclasses in other places in code.

## Describe alternatives you've considered
Keep using dataclasses for abi only in FullNodeClient.

**Comment by cptartur** [comment]
We've decided to continue using dict/typeddict in interfaces, and only use dataclasses internally.

**Comment by Solpatium** [comment]
We decided to use TypedDicts instead of dataclasses as there is no benefit from using dataclasses.

**Comment by cptartur** [comment]
Blocked by #547

**Comment by cptartur** [comment]
We're using dataclass instead
