### ISSUE TITLE
Consider the fate of the Compiler module

### ISSUE THREAD

**Issue by cptartur** [software-mansion/starknet.py#558]
### Feature Request

Should it be removed or supported once cairo-lang is deprecated?

**Comment by cptartur** [comment]
One possible approach: Create an interface between starknet.py and rust compiler of cairo 1 and modify Compiler module to utilize it. This might become quite complicated to support though, so it will need more consideration.

**Comment by cptartur** [comment]
Seems that web3.py doesn't bundle any kind of compilation and [their docs](https://web3py.readthedocs.io/en/v5/contracts.html) suggest using a completely external library. Perhaps it'd be a logical to drop the compilation module entirely.

**Comment by war-in** [comment]
#635
