### ISSUE TITLE
Propose a new structure of the library

### ISSUE THREAD

**Issue by cptartur** [software-mansion/starknet.py#562]
### Feature Request

We should create a example structure tree of the library before we proceed with any eventual refactors of the package.

**Comment by war-in** [comment]
This is my idea. Check it out and give me feedback.
Red rectangles are only visual groups just to show which files and modules are connected.
[dir_structure.drawio.pdf](https://github.com/software-mansion/starknet.py/files/10195095/Untitled.Diagram.drawio.pdf)

**Comment by war-in** [comment]
For those who are worried about the pdf file:
![image](https://user-images.githubusercontent.com/61014013/206711206-c951ef46-e86b-4479-a56b-e9393b754299.png)
![image](https://user-images.githubusercontent.com/61014013/206711256-9aba2565-6c6c-49b8-9722-ef698aebf32d.png)

**Comment by tomek0123456789** [comment]
Too much effort and change would be _too_ breaking
