### ISSUE TITLE
[BUG] Outdated code examples in README

### ISSUE THREAD

**Issue by drknzz** [software-mansion/starknet.py#568]
### What happened

The code examples in readme, showing the use of `async` and `sync` api:
- create `Client` instance which is now an abstract class
- do not use an account, making invoke throw an error

Probably the best solution would be to use only `call` and `call_sync` in the examples as they don't require an account.

### Stack trace

-

### Steps to reproduce

-

### SDK Version

0.11.0-alpha

### Python version

3.8.4

### What operating system are you using?

Mac

### Is there an existing issue for this?

- [ ] I have searched the existing issues and verified no issue exits for this problem.

**Comment by cptartur** [comment]
Where exactly this problem exists? We should probably fix it soon.

**Comment by drknzz** [comment]
I think code examples from readme should always work after a user copy pastes them into their ide. It should be somewhat of a check that the library has been installed successfully. For any further uses, they should go to the documentation web page.
Therefore we probably shouldn't be using an account there - just a pure GatewayClient and a method call.

**Comment by cptartur** [comment]
I see your point. We can do some improvements to readme.
