### ISSUE TITLE
Add lint check to verify error messages format

### ISSUE THREAD

**Issue by cptartur** [software-mansion/starknet.py#595]
### Feature Request

Connected with #594 

We could use pylint custom rule or some other tool.

**Comment by drknzz** [comment]
**pylint** does not support anything like that by default.
Also, I haven't found any other tool nor a plugin for **pylint** that would check the errors' messages.

The only option I see is potentially writing our own **pylint** [plugin](https://pylint.pycqa.org/en/latest/development_guide/how_tos/custom_checkers.html) but the preferred way of installing them is through PyPI, so I don't know if it's something we would want to do.

I'd suggest we close this issue and just keep it consistent ourselves in the future.

**Comment by cptartur** [comment]
Appreciate the research 💯 . I hoped that it'd be possible to integrate check like that with pylint nicely.

I think we can keep the issue though, in case someone comes up with a nice solution, perhaps involving some other tool.

**Comment by cptartur** [comment]
#604
