### ISSUE TITLE
Use a better theme for docs

### ISSUE THREAD

**Issue by cptartur** [software-mansion/starknet.py#618]
### Feature Request

Current theme looks a bit dated. Change it to something more modern/better looking.

**Comment by war-in** [comment]
Do you have any idea which? I've checked some of them and I don't think they're good :/
Check them out here:
https://sphinx-themes.org/#themes

**Comment by cptartur** [comment]
Book and furo look okay-ish. Press has nice looking code blocks but otherwise is pretty meh. But these would be my initial picks probably.

**Comment by war-in** [comment]
I've used them and furo is the best one for me. API section is clearer now. I will create a `Draft PR` with it so everybody can check and comment if they like it.
