### ISSUE TITLE
Remove deprecated client argument from `Contract.__init__` `Contract.from_address`

### ISSUE THREAD

**Issue by cptartur** [software-mansion/starknet.py#632]
### Feature Request

Argument `client` has been deprecated in #499 (#631) and should be removed.

**Comment by cptartur** [comment]
We have to keep it for a few versions though 😅

**Comment by crypt0xyc** [comment]
The client param should also be removed from the docs or at least include a hint that this is deprecated.
https://starknetpy.readthedocs.io/en/latest/contract.html
