### ISSUE TITLE
Benchmark crypto-cpp

### ISSUE THREAD

**Issue by war-in** [software-mansion/starknet.py#636]
### Feature Request

We would like to use more cryptography from the crypto-cpp library. If the results will be promising we will probably use crypto-cpp to replace some functions:
- private_to_stark_key
- verify
- sign
- pedersen_hash

**Comment by cptartur** [comment]
From my testing it seems:

- verify has similar performance in cpp and python
- hash is faster in cpp for longer inputs, for short python is faster
- sign is substantially lower in cpp, 6-10x slower than python implementation

`sign` is problematic enough that I'd say it currently prevents us from using crypto-cpp version at all. It is probably the most often used crypto operation in starknet.py and 6-10x slowdown would be noticeable to all users.
