### ISSUE TITLE
Sending ETH to another address StarknetChainId.TESTNET

### ISSUE THREAD

**Issue by KonstantinLitvin** [software-mansion/starknet.py#667]
Hi! I am playing with starknet.py and have an issue with sending some eth to another address, could you help, please? 

```
client = GatewayClient(TESTNET)


def get_account():
    return Account(
        client=client,
        address=load('address'),
        key_pair=KeyPair.from_private_key(key=load('private_key')),
        chain=StarknetChainId.TESTNET,
    )


async def send(recipient):
    account = get_account()

    ETH_CONTRACT = 0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7
    # When ABI is known statically just use the Contract constructor
    # contract = Contract(address=address, abi=abi, provider=account)
    # or if it is not known
    # Contract.from_address makes additional request to fetch the ABI
    abi = [

        {
            "inputs": [
                {
                    "name": "recipient",
                    "type": "felt"
                },
                {
                    "name": "amount",
                    "type": "felt"
                }
            ],
            "name": "transfer",
            "outputs": [],
            "type": "function"
        },
        {
            "inputs": [
                {
                    "name": "sender",
                    "type": "felt"
                },
                {
                    "name": "recipient",
                    "type": "felt"
                },
                {
                    "name": "amount",
                    "type": "felt"
                }
            ],
            "name": "transfer_from",
            "outputs": [],
            "type": "function"
        },
        {
            "inputs": [
                {
                    "name": "spender",
                    "type": "felt"
                },
                {
                    "name": "amount",
                    "type": "felt"
                }
            ],
            "name": "approve",
            "outputs": [],
            "type": "function"
        }

    ]

    contract = Contract(provider=account, abi=abi, address=ETH_CONTRACT)

    f = contract.functions['transfer']
    invocation = await f.invoke(
        recipient=recipient, amount=1000000, max_fee=int(1e16))
    r = await invocation.wait_for_acceptance()


if __name__ == '__main__':
    to = 0x02...dbbe9
    asyncio.run(send(to))

```
Debug output:

 File "/home/.../.../starknet_play/venv/lib/python3.9/site-packages/starknet_py/contract.py", line 85, in wait_for_acceptance
    block_number, status = await self._client.wait_for_tx(
  File "/home/.../.../starknet_play/venv/lib/python3.9/site-packages/starknet_py/net/client.py", line 159, in wait_for_tx
    raise TransactionRejectedError(
starknet_py.transaction_exceptions.TransactionRejectedError: Transaction was rejected with following starknet error: Error at pc=0:10:
Got an exception while executing a hint.
Cairo traceback (most recent call last):
Unknown location (pc=0:228)
Unknown location (pc=0:214)

Error in the called contract (0x150...fc5):
Error at pc=0:208:
Got an exception while executing a hint.
Cairo traceback (most recent call last):
Unknown location (pc=0:4056)
Unknown location (pc=0:4004)
Unknown location (pc=0:3090)
Unknown location (pc=0:3111)

Error in the called contract (0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7):
Error at pc=0:104:
Got an exception while executing a hint.
Cairo traceback (most recent call last):
Unknown location (pc=0:1678)
Unknown location (pc=0:1664)

Error in the called contract (0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7):
Error at pc=0:1344:
An ASSERT_EQ instruction failed: 10:3 != 10:2..

**Comment by war-in** [comment]
Hey, I believe the problem is with the abi. Try to use one from the [starkscan](https://starkscan.co/contract/0x048624e084dc68d82076582219c7ed8cb0910c01746cca3cd72a28ecfe07e42d#class)

**Comment by KonstantinLitvin** [comment]
Yes, It works! Thank you!
