### ISSUE TITLE
Update `codesnippet`'s `start-after` and `end_before`

### ISSUE THREAD

**Issue by war-in** [software-mansion/starknet.py#698]
### Feature Request

I am working on code examples for `GatewayClient`. There are two methods:
- `estimate_fee`
- `estimate_fee_bulk`

When I specify 
```
:start-after: docs-start: estimate_fee
:end-before: docs-end: estimate_fee
```
 the `codesnippet` also takes lines between `docs-start: estimate_fee_bulk` and `docs-end: estimate_fee_bulk`.
 
 
<img width="688" alt="image" src="https://user-images.githubusercontent.com/61014013/214649403-31489d0a-bfba-46ac-8008-ce46747d39d7.png">

Would be perfect to enforce `codesnippet` to take the lines only if the match is perfect

**Comment by war-in** [comment]
@drknzz is it possible?

**Comment by drknzz** [comment]
That's a shame. Currently it uses `Reader`'s methods `start_filter` and `end_filter` to find the specified strings. For this to work, it would just have to be swapped to use something like `match` from regex.

**Comment by drknzz** [comment]
Maybe it could be implemented as an optional flag to make sure nothing from current documentation is broken.
```
.. codesnippet:: ../../starknet_py/tests/e2e/docs/guide/test_resolving_proxies.py
    :language: python
    :dedent: 4
    :start-after: docs-1: start
    :end-before: docs-1: end
    :exact-match:
```
