### ISSUE TITLE
Move `properties` to the top

### ISSUE THREAD

**Issue by war-in** [software-mansion/starknet.py#716]
### Feature Request

Properties are now at the bottom of the class API. There should be an option in the `autoclass` to move them above methods.

**Comment by cptartur** [comment]
Sphinx has two issues open that seem to be related to this? 

https://github.com/sphinx-doc/sphinx/issues/5270

https://github.com/sphinx-doc/sphinx/issues/5271

This might not be resolvable on our side.

**Comment by drknzz** [comment]
After some research, it seems it would be really hard to even implement this by ourselves on our side. It would require lots of tweaking around with autodoc parser's internals.

**Comment by cptartur** [comment]
Marking as blocked now, once sphinx resolves the issue with source order not being preserved, I think it can be resolvable by simply arranging the code of a class in specific order.
