### ISSUE TITLE
StarknetChainId not Optional

### ISSUE THREAD

**Issue by drknzz** [software-mansion/starknet.py#719]
### Feature Request

Currently, chain parameter in `Account.deploy_account` is required. It seems though, it could be optional, as the `chain` could be taken from required `client` parameter.

**Comment by cptartur** [comment]
`Client` ABC doesn't expose the `chain` parameter. This would require changes in the interface to be resolvable.

**Comment by drknzz** [comment]
Yes, but the `chain` could be created from `net` property in `Client`.

**Comment by cptartur** [comment]
Right, it could, though the `Network` returned by `net` could be a string literal, a dict, etc. This would have to be handled. If you think it's worth it to do so, let's keep this issue.

**Comment by cptartur** [comment]
As per #738 `net` will be removed from `Client` interface.
