### ISSUE TITLE
Deprecation warnings in documentation

### ISSUE THREAD

**Issue by drknzz** [software-mansion/starknet.py#721]
### Feature Request

Currently, deprecation warnings are only present in the code and migration guide. We should add some attention / warning blocks to documentation for each deprecation.

**Comment by cptartur** [comment]
Sphinx actually supports some kind of deprecation message out of the box if `.. deprecated:: version` is included in the docstring.

It renders to something like this
![image](https://user-images.githubusercontent.com/52135326/215817319-92bc76f6-b29e-4703-b685-949b7505f2c3.png)

This is not very visible in my opinion. A possible solution would be to change the formatting of `.. deprecated::` so it's more visible. This doesn't however address the cases where we forget to include the deprecation in the docstring and it functions only as a warning in code.
