### ISSUE TITLE
ModuleNotFoundError: No module named 'starknet_py.net.gateway_client'

### ISSUE THREAD

**Issue by crypt0xyc** [software-mansion/starknet.py#722]
### What happened

Trying out simple code snippets (from doc pages) fails because some files are missing in the installed package.

For example, the folder contents in `/.venv/lib/python3.10/site-packages/starknet_py/net/` are only `__init__.py`, `client.py` and the `account` subfolder. Comparing this to the contents in the GitHub repo, there are apparently multiple files that are missing, such as gateway_client.py, resulting in compile time errors when trying to import these missing modules.
More specifically, `from starknet_py.net.gateway_client import GatewayClient` throws a ModuleNotFound error.

Starknet_py has been installed correctly and many of the modules are functioning as expected (for example, importing Contract from the starknet_py.contract module works fine). The installation was done according to the docs by `pip install starknet-py` and later (for additional verification) was run again with `pip install --upgrade starknet-py`.

![image](https://user-images.githubusercontent.com/95582158/215490691-5cf38682-9041-486b-8a55-a39d0484a691.png)

### Stack trace

```
Traceback (most recent call last):
  File "/home/crypt0xyc/projects/starknet-arb/jediswap_prices.py", line 2, in <module>
    from starknet_py.net.gateway_client import GatewayClient
ModuleNotFoundError: No module named 'starknet_py.net.gateway_client'
```

### Steps to reproduce

1. pip install starknet-py
2. from starknet_py.net.gateway_client import GatewayClient

### SDK Version

0.1.3a0

### Python version

3.10.6

### What operating system are you using?

Linux

### Is there an existing issue for this?

- [X] I have searched the existing issues and verified no issue exits for this problem.

**Comment by drknzz** [comment]
Hey, unfortunately, starknet.py does not support Python 3.10.
The only currently supported versions are 3.8 and 3.9.
