### ISSUE TITLE
Consider setting up a merge queue

### ISSUE THREAD

**Issue by cptartur** [software-mansion/starknet.py#745]
### Feature Request

https://github.blog/changelog/2023-02-08-pull-request-merge-queue-public-beta/

Let's investigate if it is useful for us and set it up if so.

**Comment by cptartur** [comment]
This will require updating our workflows to trigger on merge queue operations.

https://docs.github.com/en/enterprise-cloud@latest/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions

**Comment by cptartur** [comment]
I've reviewed how merge queues work and I think it is not useful in our case. PRs stay in the queue for some (configurable) amount of time, after which they are merged.

I think the cases where we have multiple PRs wanting to be merged within minutes from each is is low, that requiring merge queue will be more limiting than beneficial.

**Comment by drknzz** [comment]
Great, no point in introducing something that's just restrictive in our case. 
Good job on the research 👍
