### ISSUE TITLE
[BUG] starknet_py.net.account.account.account not find

### ISSUE THREAD

**Issue by BaiShaojie123123** [software-mansion/starknet.py#751]
### What happened

mac inter
pip3 install starknet-py
Successfully installed starknet-py-0.1.3a0
python version 3.10

### Stack trace

> pip install starknet-py -i https://pypi.python.org/simple/

Looking in indexes: https://pypi.python.org/simple/
Collecting starknet-py
  Using cached starknet.py-0.1.3a0-py3-none-any.whl (79 kB)
Requirement already satisfied: asgiref<4.0.0,>=3.4.1 in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from starknet-py) (3.6.0)
Requirement already satisfied: cairo-lang==0.6.2 in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from starknet-py) (0.6.2)
Requirement already satisfied: pytest in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from cairo-lang==0.6.2->starknet-py) (6.2.5)
Requirement already satisfied: pytest-asyncio in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from cairo-lang==0.6.2->starknet-py) (0.20.3)
Requirement already satisfied: PyYAML in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from cairo-lang==0.6.2->starknet-py) (5.4.1)
Requirement already satisfied: pipdeptree in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from cairo-lang==0.6.2->starknet-py) (2.3.3)
Requirement already satisfied: typeguard in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from cairo-lang==0.6.2->starknet-py) (2.13.3)
Requirement already satisfied: frozendict==1.2 in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from cairo-lang==0.6.2->starknet-py) (1.2)
Requirement already satisfied: marshmallow>=3.2.1 in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from cairo-lang==0.6.2->starknet-py) (3.19.0)
Requirement already satisfied: marshmallow-oneofschema in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from cairo-lang==0.6.2->starknet-py) (3.0.1)
Requirement already satisfied: eth-hash[pycryptodome]==0.2.0 in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from cairo-lang==0.6.2->starknet-py) (0.2.0)
Requirement already satisfied: mpmath in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from cairo-lang==0.6.2->starknet-py) (1.0.0)
Requirement already satisfied: marshmallow-dataclass>=7.1.0 in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from cairo-lang==0.6.2->starknet-py) (8.5.11)
Requirement already satisfied: cachetools in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from cairo-lang==0.6.2->starknet-py) (5.2.0)
Requirement already satisfied: sympy in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from cairo-lang==0.6.2->starknet-py) (1.6)
Requirement already satisfied: lark-parser in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from cairo-lang==0.6.2->starknet-py) (0.12.0)
Requirement already satisfied: ecdsa in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from cairo-lang==0.6.2->starknet-py) (0.16.0)
Requirement already satisfied: marshmallow-enum in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from cairo-lang==0.6.2->starknet-py) (1.5.1)
Requirement already satisfied: numpy in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from cairo-lang==0.6.2->starknet-py) (1.24.1)
Requirement already satisfied: fastecdsa in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from cairo-lang==0.6.2->starknet-py) (2.3.0)
Requirement already satisfied: Web3 in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from cairo-lang==0.6.2->starknet-py) (5.31.1)
Requirement already satisfied: aiohttp in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from cairo-lang==0.6.2->starknet-py) (3.8.3)
Requirement already satisfied: prometheus-client in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from cairo-lang==0.6.2->starknet-py) (0.16.0)
Requirement already satisfied: pycryptodome<4,>=3.6.6 in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from eth-hash[pycryptodome]==0.2.0->cairo-lang==0.6.2->starknet-py) (3.15.0)
Requirement already satisfied: packaging>=17.0 in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from marshmallow>=3.2.1->cairo-lang==0.6.2->starknet-py) (21.3)
Requirement already satisfied: typing-inspect>=0.8.0 in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from marshmallow-dataclass>=7.1.0->cairo-lang==0.6.2->starknet-py) (0.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from aiohttp->cairo-lang==0.6.2->starknet-py) (6.0.2)
Requirement already satisfied: attrs>=17.3.0 in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from aiohttp->cairo-lang==0.6.2->starknet-py) (22.1.0)
Requirement already satisfied: yarl<2.0,>=1.0 in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from aiohttp->cairo-lang==0.6.2->starknet-py) (1.8.1)
Requirement already satisfied: frozenlist>=1.1.1 in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from aiohttp->cairo-lang==0.6.2->starknet-py) (1.3.3)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from aiohttp->cairo-lang==0.6.2->starknet-py) (2.1.1)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from aiohttp->cairo-lang==0.6.2->starknet-py) (4.0.2)
Requirement already satisfied: aiosignal>=1.1.2 in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from aiohttp->cairo-lang==0.6.2->starknet-py) (1.2.0)
Requirement already satisfied: six>=1.9.0 in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from ecdsa->cairo-lang==0.6.2->starknet-py) (1.16.0)
Requirement already satisfied: py>=1.8.2 in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from pytest->cairo-lang==0.6.2->starknet-py) (1.11.0)
Requirement already satisfied: iniconfig in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from pytest->cairo-lang==0.6.2->starknet-py) (1.1.1)
Requirement already satisfied: toml in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from pytest->cairo-lang==0.6.2->starknet-py) (0.10.2)
Requirement already satisfied: pluggy<2.0,>=0.12 in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from pytest->cairo-lang==0.6.2->starknet-py) (1.0.0)
Requirement already satisfied: jsonschema<5,>=3.2.0 in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from Web3->cairo-lang==0.6.2->starknet-py) (3.2.0)
Requirement already satisfied: eth-account<0.6.0,>=0.5.9 in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from Web3->cairo-lang==0.6.2->starknet-py) (0.5.9)
Requirement already satisfied: eth-typing<3.0.0,>=2.0.0 in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from Web3->cairo-lang==0.6.2->starknet-py) (2.3.0)
Requirement already satisfied: ipfshttpclient==0.8.0a2 in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from Web3->cairo-lang==0.6.2->starknet-py) (0.8.0a2)
Requirement already satisfied: eth-abi<3.0.0,>=2.0.0b6 in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from Web3->cairo-lang==0.6.2->starknet-py) (2.2.0)
Requirement already satisfied: eth-utils<2.0.0,>=1.9.5 in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from Web3->cairo-lang==0.6.2->starknet-py) (1.9.5)
Requirement already satisfied: eth-rlp<0.3 in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from Web3->cairo-lang==0.6.2->starknet-py) (0.2.1)
Requirement already satisfied: hexbytes<1.0.0,>=0.1.0 in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from Web3->cairo-lang==0.6.2->starknet-py) (0.2.3)
Requirement already satisfied: protobuf==3.19.5 in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from Web3->cairo-lang==0.6.2->starknet-py) (3.19.5)
Requirement already satisfied: requests<3.0.0,>=2.16.0 in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from Web3->cairo-lang==0.6.2->starknet-py) (2.28.1)
Requirement already satisfied: lru-dict<2.0.0,>=1.1.6 in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from Web3->cairo-lang==0.6.2->starknet-py) (1.1.8)
Requirement already satisfied: websockets<10,>=9.1 in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from Web3->cairo-lang==0.6.2->starknet-py) (9.1)
Requirement already satisfied: multiaddr>=0.0.7 in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from ipfshttpclient==0.8.0a2->Web3->cairo-lang==0.6.2->starknet-py) (0.0.9)
Requirement already satisfied: parsimonious<0.9.0,>=0.8.0 in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from eth-abi<3.0.0,>=2.0.0b6->Web3->cairo-lang==0.6.2->starknet-py) (0.8.1)
Requirement already satisfied: eth-keyfile<0.6.0,>=0.5.0 in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from eth-account<0.6.0,>=0.5.9->Web3->cairo-lang==0.6.2->starknet-py) (0.5.1)
Requirement already satisfied: rlp<3,>=1.0.0 in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from eth-account<0.6.0,>=0.5.9->Web3->cairo-lang==0.6.2->starknet-py) (2.0.1)
Requirement already satisfied: eth-keys<0.4.0,>=0.3.4 in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from eth-account<0.6.0,>=0.5.9->Web3->cairo-lang==0.6.2->starknet-py) (0.3.4)
Requirement already satisfied: bitarray<3,>=1.2.1 in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from eth-account<0.6.0,>=0.5.9->Web3->cairo-lang==0.6.2->starknet-py) (2.6.0)
Requirement already satisfied: cytoolz<1.0.0,>=0.10.1 in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from eth-utils<2.0.0,>=1.9.5->Web3->cairo-lang==0.6.2->starknet-py) (0.12.0)
Requirement already satisfied: pyrsistent>=0.14.0 in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from jsonschema<5,>=3.2.0->Web3->cairo-lang==0.6.2->starknet-py) (0.18.1)
Requirement already satisfied: setuptools in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from jsonschema<5,>=3.2.0->Web3->cairo-lang==0.6.2->starknet-py) (65.5.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from packaging>=17.0->marshmallow>=3.2.1->cairo-lang==0.6.2->starknet-py) (3.0.9)
Requirement already satisfied: certifi>=2017.4.17 in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from requests<3.0.0,>=2.16.0->Web3->cairo-lang==0.6.2->starknet-py) (2022.12.7)
Requirement already satisfied: idna<4,>=2.5 in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from requests<3.0.0,>=2.16.0->Web3->cairo-lang==0.6.2->starknet-py) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from requests<3.0.0,>=2.16.0->Web3->cairo-lang==0.6.2->starknet-py) (1.26.12)
Requirement already satisfied: typing-extensions>=3.7.4 in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from typing-inspect>=0.8.0->marshmallow-dataclass>=7.1.0->cairo-lang==0.6.2->starknet-py) (4.4.0)
Requirement already satisfied: mypy-extensions>=0.3.0 in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from typing-inspect>=0.8.0->marshmallow-dataclass>=7.1.0->cairo-lang==0.6.2->starknet-py) (0.4.3)
Requirement already satisfied: toolz>=0.8.0 in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from cytoolz<1.0.0,>=0.10.1->eth-utils<2.0.0,>=1.9.5->Web3->cairo-lang==0.6.2->starknet-py) (0.12.0)
Requirement already satisfied: varint in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from multiaddr>=0.0.7->ipfshttpclient==0.8.0a2->Web3->cairo-lang==0.6.2->starknet-py) (1.0.2)
Requirement already satisfied: netaddr in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from multiaddr>=0.0.7->ipfshttpclient==0.8.0a2->Web3->cairo-lang==0.6.2->starknet-py) (0.8.0)
Requirement already satisfied: base58 in /Users/baishaojie/opt/anaconda3/envs/python_blockchain_tools/lib/python3.10/site-packages (from multiaddr>=0.0.7->ipfshttpclient==0.8.0a2->Web3->cairo-lang==0.6.2->starknet-py) (2.1.1)
Installing collected packages: starknet-py
Successfully installed starknet-py-0.1.3a0

### Steps to reproduce

1.  pip install starknet-py -i https://pypi.python.org/simple/     

### SDK Version

starknet-py-0.1.3a0

### Python version

3.10

### What operating system are you using?

Mac

### Is there an existing issue for this?

- [X] I have searched the existing issues and verified no issue exits for this problem.

**Comment by drknzz** [comment]
Hey there. Unfortunately starknet.py currently works only with python3.8 and 3.9.
Python 3.10 is not yet supported.
