### ISSUE TITLE
Remove deprecated compute_invoke_hash

### ISSUE THREAD

**Issue by drknzz** [software-mansion/starknet.py#768]
_Originally posted by @cptartur in https://github.com/software-mansion/starknet.py/pull/592#discussion_r1073292122_

**Comment by cptartur** [comment]
Blocked until #592 is merged

**Comment by cptartur** [comment]
We should wait until after 0.11.0 with removal.

**Comment by drknzz** [comment]
> We should wait until after 0.11.0 with removal.

What would be the justification for that?

**Comment by cptartur** [comment]
It will officially become deprecated (released) alongside with 0.11.0 update. I think we better wait at least one version before complete removal.
