### ISSUE TITLE
Remove transaction dataclasses in `client_models.py`

### ISSUE THREAD

**Issue by drknzz** [software-mansion/starknet.py#774]
### Feature Request

New transaction dataclasses have been added in #649, leaving us with 2 dataclasses for each transaction:
```
net/models/transaction.py
net/client_models.py
```

We should possibly remove the old transaction classes and replace their usages with the new ones.

**Comment by cptartur** [comment]
Blocked after 0.11.0. This should be a part of the general refactor I think.

**Comment by cptartur** [comment]
Transactions returned from gateway are different than the ones we send. They cannot be combined.
