### ISSUE TITLE
Starknet ID domains integration

### ISSUE THREAD

**Issue by fricoben** [software-mansion/starknet.py#789]
### Feature Request

Hello ! 

I'm [Ben](https://twitter.com/Fricoben) cofounder of Starknet ID. We would love to add Starknet ID resolving functions to starknet PY as we did with the other Starknet Libraries.

Here is some explanation https://github.com/starknet-id/naming_contract/issues/8

Tell me if it's ok and a member of our team will make this implementation !

**Comment by cptartur** [comment]
Hey, let me discuss this with the rest of the team and will get back to you 👍

**Comment by fricoben** [comment]
Hey Did you have some time to discuss about it ?

**Comment by cptartur** [comment]
Hey, could you provide us with a more in depth plan on how integration like that would look like i.e. what methods would be added, where and how would they be integrated?  

After an internal discussion we've had, we'd prefer not to included functionalities that will propagate through the library requiring us to support and maintain them in multiple places.
