### ISSUE TITLE
Setup an option to exclude issues from stalebot

### ISSUE THREAD

**Issue by cptartur** [software-mansion/starknet.py#794]
### Feature Request

There should be a solution (like a label or specific tag in name) to disable stalebot for issue. We have some issues that will not be resolved for a longer while and there should be a way of excluding them from stalebot.

**Comment by drknzz** [comment]
There already are such labels, see [here](https://github.com/software-mansion/starknet.py/blob/development/.github/stale.yml#L6).
I've created a `pinned` label, which wasn't in the repo.
