### ISSUE TITLE
[BUG] Contract with stateMutability fields in their abis cause exception on Contract.from_address with FullNodeClient

### ISSUE THREAD

**Issue by thomas-gallop** [software-mansion/starknet.py#798]
### What happened

I attempted to load the contract for the Aspect: Shared Storefront and received marshmellow ValidationError

### Stack trace

Fetching contract 0x03090623ea32d932ca1236595076b00702e7d860696faf300ca9eb13bfe0a78c
Traceback (most recent call last):
  File "/src/skn_client.py", line 35, in get_contract
    r = await Contract.from_address(client=self.full_node_client, address=contract_address, proxy_config=self.proxy_config)
  File "/usr/local/lib/python3.9/site-packages/starknet_py/contract.py", line 525, in from_address
    abi = await ContractAbiResolver(
  File "/usr/local/lib/python3.9/site-packages/starknet_py/proxy/contract_abi_resolver.py", line 86, in resolve
    return await self.resolve_abi()
  File "/usr/local/lib/python3.9/site-packages/starknet_py/proxy/contract_abi_resolver.py", line 112, in resolve_abi
    contract_class = await self.client.get_class_by_hash(implementation)
  File "/usr/local/lib/python3.9/site-packages/starknet_py/net/full_node_client.py", 
line 271, in get_class_by_hash
    DeclaredContract, DeclaredContractSchema().load(res, unknown=EXCLUDE)
  File "/usr/local/lib/python3.9/site-packages/marshmallow/schema.py", line 722, in load
    return self._do_load(
  File "/usr/local/lib/python3.9/site-packages/marshmallow/schema.py", line 909, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'abi': {9: {'stateMutability': ['Unknown field.']}, 10: {'stateMutability': ['Unknown field.']}, 11: {'stateMutability': ['Unknown field.']}, 12: {'stateMutability': ['Unknown field.']}, 13: {'stateMutability': ['Unknown field.']}, 14: {'stateMutability': ['Unknown field.']}, 15: {'stateMutability': ['Unknown field.']}, 16: {'stateMutability': ['Unknown field.']}, 17: {'stateMutability': ['Unknown field.']}, 18: {'stateMutability': ['Unknown field.']}, 19: {'stateMutability': ['Unknown field.']}, 20: {'stateMutability': ['Unknown field.']}}}  

### Steps to reproduce

import asyncio
from dotenv import load_dotenv
from starknet_py.contract import Contract
from starknet_py.proxy.contract_abi_resolver import ProxyConfig
from starknet_py.net.full_node_client import FullNodeClient
from starknet_py.proxy.proxy_check import (
    ArgentProxyCheck,
    OpenZeppelinProxyCheck,
)

async def main():
    test_contract_addy = '0x03090623ea32d932ca1236595076b00702e7d860696faf300ca9eb13bfe0a78c'
    my_proxy_config = ProxyConfig(
            proxy_checks=[ArgentProxyCheck(), OpenZeppelinProxyCheck()]  # Add Custom ProxyChecks Here
    )
    full_node_client = FullNodeClient(node_url="https://alpha-mainnet.starknet.io", net="mainnet")
    print(f"Fetching contract {test_contract_addy}")
    try:
        contract = await Contract.from_address(client=full_node_client, address=test_contract_addy, proxy_config=my_proxy_config)
    except Exception:
        traceback.print_exc()

asyncio.run(main())

### SDK Version

0.14.0-alpha

### Python version

3.9

### What operating system are you using?

Linux

### Is there an existing issue for this?

- [X] I have searched the existing issues and verified no issue exits for this problem.

**Comment by drknzz** [comment]
Hey, this little modified code of yours works for me:
```
test_contract_addy = '0x03090623ea32d932ca1236595076b00702e7d860696faf300ca9eb13bfe0a78c'
gateway_client = GatewayClient(net="mainnet")
contract = await Contract.from_address(client=gateway_client, address=test_contract_addy, proxy_config=True)
```

**Comment by thomas-gallop** [comment]
> Hey, this little modified code of yours works for me:
> 
> ```
> test_contract_addy = '0x03090623ea32d932ca1236595076b00702e7d860696faf300ca9eb13bfe0a78c'
> gateway_client = GatewayClient(net="mainnet")
> contract = await Contract.from_address(client=gateway_client, address=test_contract_addy, proxy_config=True)
> ```

Thanks for the heads up.  Can confirm, using a Gateway client ABI is able to validate.
