### ISSUE TITLE
Support sending Declare v2 transaction

### ISSUE THREAD

**Issue by cptartur** [software-mansion/starknet.py#802]
### Feature Request

Create a dataclass for `Declare v2` and support it in the necessary methods.

**Comment by drknzz** [comment]
Kinda tied to #816 with `NewContractClass`

**Comment by cptartur** [comment]
> Kinda tied to #816 with `NewContractClass`

What I mostly meant with this issue is sending Declare v2 transactions. Renaming.

**Comment by cptartur** [comment]
Blocked by `https://github.com/starkware-libs/cairo-lang/blob/12ca9e91bbdc8a423c63280949c7e34382792067/src/starkware/starknet/core/os/contract_class/compiled_class_hash.py#L40`. `CompiledClass` expects the old casm json format and is incompatible with new Cairo1 compiler outputs. Until this is addressed we cannot compute compiled class hashes required for declare v2.

**Comment by cptartur** [comment]
Computing compiled_class_hash aside, this can (an will be) done. User will have to provide `compiled_class_hash` for now.
