### ISSUE TITLE
[BUG] `deploy_sync` seems to be blocking

### ISSUE THREAD

**Issue by Pet3ris** [software-mansion/starknet.py#82]
Hey thanks for developing `starknet.py`, awesome lib we are starting to use at https://yagi.fi! Friendly (possible) bug report.

I'm trying to deploy an account contract using `deploy_sync` but it hangs rather than returning the pending tx (which is what `invoke_sync` does).

## Python version
3.8

## Expected Behavior
Should return pending tx.

## Current Behavior
Hangs.

## Possible Solution
Match `invoke_sync` behavior with `deploy_sync`.

## Steps to Reproduce
```python
source_code = Path("contracts/Account.cairo").read_text("utf-8")
result = Contract.deploy_sync(
    client=Client("testnet"),
    compilation_source=source_code,
    constructor_args={
        "_public_key": public_key
    }
)
```

## Context (Environment)
Not able to deploy an account contract using `starknet.py`.

## Detailed Description
-

## Possible Implementation
-

**Comment by Arcticae** [comment]
You're totally right! We're going to align the behavior and release it with the next version

**Comment by Pet3ris** [comment]
Awesome - thanks @Arcticae!
