### ISSUE TITLE
Fix dependabot `requirements.txt` generate action

### ISSUE THREAD

**Issue by cptartur** [software-mansion/starknet.py#846]
### Feature Request

Seems like dependabot `generate` action does no longer work due to permission problem. 

See https://github.com/software-mansion/starknet.py/pull/828

It most likely can be fixed by elevating the permission for this specific action. From what I understand dependabot `GITHUB_TOKEN` is [read only by default](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#changing-github_token-permissions) and it's preventing it from commiting updated `requirerments.txt`.

**Comment by cptartur** [comment]
Tagging @THenry14 can you verify if what I found about dependabot permissions is correct?

**Comment by THenry14** [comment]
yeah, sound about right
