### ISSUE TITLE
Do not use `installer.modern-installation false` in actions

### ISSUE THREAD

**Issue by war-in** [software-mansion/starknet.py#882]
### Feature Request

<img width="863" alt="image" src="https://user-images.githubusercontent.com/61014013/226340949-f1b76ddd-301c-4da0-ad41-e183e5cb50a4.png">

https://github.com/software-mansion/starknet.py/pull/881

**Comment by drknzz** [comment]
[A run without `installer.modern-installation false` containing the fail.](https://github.com/software-mansion/starknet.py/actions/runs/4574427141/jobs/8076205962)
