### ISSUE TITLE
Restore test

### ISSUE THREAD

**Issue by war-in** [software-mansion/starknet.py#893]
### Feature Request

- test_declare_v2_tx

**Comment by cptartur** [comment]
I'd give this a higher priority so it's visible.

**Comment by drknzz** [comment]
Blocked by `starknet-sierra-compile` executable not being shipped for different platforms in cairo-lang package.
Devnet uses `compile_class_hash` from cairo-lang.

**Comment by war-in** [comment]
compiler path can be passed while creating devnet
https://github.com/Shard-Labs/starknet-devnet/releases/tag/v0.5.0a1
